name: "Workflow Action Setup"
description: "Setup container with uv and dependencies for ci workflows"

inputs:
  python-version:
    description: "Python version to use"
    required: false
    default: "3.12"
  uv-version:
    description: "Version of uv to install"
    required: false
    default: "0.5.7"

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: ${{ inputs.uv-version }}
        enable-cache: true
        cache-dependency-glob: "requirements/**.txt"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Setup SSH
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SECRET_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Install project dependencies
      shell: bash
      run: make install ENV=action
