"""init

Revision ID: 023e7f96f47f
Revises:
Create Date: 2024-10-25 11:24:28.751003

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision: str = "023e7f96f47f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("username", sa.String(length=25), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modified_by_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=False)
    op.create_table(
        "group",
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("short_name", sa.String(length=25), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modified_by_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_group_short_name"), "group", ["short_name"], unique=False)
    op.create_table(
        "observatory",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("short_name", sa.String(length=50), nullable=True),
        sa.Column(
            "observatory_type",
            sa.Enum(
                "SPACE_BASED",
                "GROUND_BASED",
                name="observatory_type",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modified_by_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "permission",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_permission_name"), "permission", ["name"], unique=True)
    op.create_table(
        "role",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modified_by_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "group_invite",
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("receiver_email", sa.String(length=100), nullable=False),
        sa.Column("receiver_id", sa.UUID(), nullable=True),
        sa.Column("sender_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modified_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["receiver_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "group_observatory",
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("observatory_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["observatory_id"],
            ["observatory.id"],
        ),
        sa.PrimaryKeyConstraint("group_id", "observatory_id"),
    )
    op.create_table(
        "group_role",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modified_by_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "role_permission",
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permission.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.PrimaryKeyConstraint("permission_id", "role_id"),
    )
    op.create_table(
        "telescope",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("short_name", sa.String(length=50), nullable=True),
        sa.Column("observatory_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modified_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["observatory_id"],
            ["observatory.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_group",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "group_id"),
    )
    op.create_table(
        "user_role",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    op.create_table(
        "group_role_permission",
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.Column("group_role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_role_id"],
            ["group_role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permission.id"],
        ),
        sa.PrimaryKeyConstraint("permission_id", "group_role_id"),
    )
    op.create_table(
        "instrument",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("short_name", sa.String(length=50), nullable=True),
        sa.Column("telescope_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modified_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["telescope_id"],
            ["telescope.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_group_role",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("group_role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_role_id"],
            ["group_role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "group_role_id"),
    )
    op.create_table(
        "footprint",
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column(
            "polygon",
            Geography(
                geometry_type="POLYGON",
                srid=4326,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modified_by_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("footprint")
    op.drop_table("user_group_role")
    op.drop_table("instrument")
    op.drop_table("group_role_permission")
    op.drop_table("user_role")
    op.drop_table("user_group")
    op.drop_table("telescope")
    op.drop_table("role_permission")
    op.drop_table("group_role")
    op.drop_table("group_observatory")
    op.drop_table("group_invite")
    op.drop_table("role")
    op.drop_index(op.f("ix_permission_name"), table_name="permission")
    op.drop_table("permission")
    op.drop_table("observatory")
    op.drop_index(op.f("ix_group_short_name"), table_name="group")
    op.drop_table("group")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    sa.Enum(name="observatory_type").drop(op.get_bind(), checkfirst=False)
    # ### end Alembic commands ###
