"""Adding observation and schedule tables

Revision ID: a3fa043a00e9
Revises: 023e7f96f47f
Create Date: 2024-12-27 10:13:56.979596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3fa043a00e9'
down_revision: Union[str, None] = '023e7f96f47f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_by_id', sa.UUID(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.ForeignKeyConstraint(['modified_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('observation',
    sa.Column('instrument_id', sa.UUID(), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('object_name', sa.String(length=100), nullable=False),
    sa.Column('pointing_ra', sa.Float(precision=5), nullable=False),
    sa.Column('pointing_dec', sa.Float(precision=5), nullable=False),
    sa.Column('date_range_begin', sa.DateTime(), nullable=False),
    sa.Column('date_range_end', sa.DateTime(), nullable=False),
    sa.Column('external_observation_id', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('exposure_time', sa.Float(precision=2), nullable=True),
    sa.Column('reason', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('proposal_reference', sa.String(length=100), nullable=True),
    sa.Column('object_ra', sa.Float(precision=5), nullable=True),
    sa.Column('object_dec', sa.Float(precision=5), nullable=True),
    sa.Column('pointing_angle', sa.Float(), nullable=True),
    sa.Column('depth_value', sa.Float(precision=2), nullable=True),
    sa.Column('depth_unit', sa.String(length=50), nullable=True),
    sa.Column('central_wavelength', sa.Float(precision=2), nullable=True),
    sa.Column('bandwidth', sa.Float(precision=2), nullable=True),
    sa.Column('filter_name', sa.String(length=50), nullable=True),
    sa.Column('t_resolution', sa.Float(), nullable=True),
    sa.Column('em_res_power', sa.Float(), nullable=True),
    sa.Column('o_ucd', sa.String(), nullable=True),
    sa.Column('pol_states', sa.String(), nullable=True),
    sa.Column('pol_xel', sa.String(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('tracking_type', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('modified_by_id', sa.UUID(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.ForeignKeyConstraint(['modified_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('observation')
    op.drop_table('schedule')
    # ### end Alembic commands ###
