"""add instrument metadata parameters

Revision ID: 201d0dd6710f
Revises: 438a1fe7c75c
Create Date: 2025-04-09 16:34:23.524925

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "201d0dd6710f"
down_revision: Union[str, None] = "438a1fe7c75c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "filter",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("peak_wavelength", sa.Float(), nullable=False),
        sa.Column("min_wavelength", sa.Float(), nullable=False),
        sa.Column("max_wavelength", sa.Float(), nullable=False),
        sa.Column("is_operational", sa.Boolean(), nullable=False),
        sa.Column("sensitivity_depth_unit", sa.String(length=50), nullable=True),
        sa.Column("sensitivity_depth", sa.Float(), nullable=True),
        sa.Column("sensitivity_time_seconds", sa.Float(), nullable=True),
        sa.Column("reference_url", sa.String(length=256), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "instrument_filter",
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("filter_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["filter_id"],
            ["filter.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.id"],
        ),
        sa.PrimaryKeyConstraint("instrument_id", "filter_id"),
    )

    # We need to give the required columns a default value that will be assigned
    # to the existing TESS observatory package from a previous migration
    op.add_column(
        "instrument",
        sa.Column(
            "type", sa.String(length=50), nullable=False, server_default="photometric"
        ),
    )
    op.add_column(
        "instrument", sa.Column("reference_url", sa.String(length=256), nullable=True)
    )
    op.add_column(
        "instrument",
        sa.Column(
            "is_operational", sa.Boolean(), nullable=False, server_default="True"
        ),
    )
    op.add_column(
        "observatory", sa.Column("reference_url", sa.String(length=256), nullable=True)
    )
    op.add_column(
        "observatory",
        sa.Column(
            "is_operational", sa.Boolean(), nullable=False, server_default="True"
        ),
    )
    op.add_column(
        "telescope", sa.Column("reference_url", sa.String(length=256), nullable=True)
    )
    op.add_column(
        "telescope",
        sa.Column(
            "is_operational", sa.Boolean(), nullable=False, server_default="True"
        ),
    )
    # ### end Alembic commands ###

    # Drop the default values now that they've been assigned to the existing observatory package objects
    op.alter_column("instrument", "type", server_default=None)
    op.alter_column("instrument", "is_operational", server_default=None)
    op.alter_column("observatory", "is_operational", server_default=None)
    op.alter_column("telescope", "is_operational", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telescope", "is_operational")
    op.drop_column("telescope", "reference_url")
    op.drop_column("observatory", "is_operational")
    op.drop_column("observatory", "reference_url")
    op.drop_column("instrument", "is_operational")
    op.drop_column("instrument", "reference_url")
    op.drop_column("instrument", "type")
    op.drop_table("instrument_filter")
    op.drop_table("filter")
    # ### end Alembic commands ###
