"""add instrument metadata parameters

Revision ID: 0f2036717762
Revises: 438a1fe7c75c
Create Date: 2025-04-23 12:48:30.301710

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import orm, select

from across_server.core.enums import InstrumentType
from migrations.versions.model_snapshots.models_2025_04_23 import (
    Observatory,
)

# revision identifiers, used by Alembic.
revision: str = "0f2036717762"
down_revision: Union[str, None] = "438a1fe7c75c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

OBSERVATORY = {
    "name": "Transiting Exoplanet Survey Satellite",
    "short_name": "TESS",
    "observatory_type": "SPACE_BASED",
    "reference_url": "https://science.nasa.gov/mission/tess/",
    "telescopes": [
        {
            "name": "Transiting Exoplanet Survey Satellite",
            "short_name": "TESS",
            "instruments": [
                {
                    "name": "Transiting Exoplanet Survey Satellite",
                    "short_name": "TESS",
                    "type": InstrumentType.PHOTOMETRIC.value,
                }
            ],
        }
    ],
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "filter",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("peak_wavelength", sa.Float(), nullable=True),
        sa.Column("min_wavelength", sa.Float(), nullable=False),
        sa.Column("max_wavelength", sa.Float(), nullable=False),
        sa.Column(
            "is_operational", sa.Boolean(), nullable=False, server_default="True"
        ),
        sa.Column("sensitivity_depth_unit", sa.String(length=50), nullable=True),
        sa.Column("sensitivity_depth", sa.Float(), nullable=True),
        sa.Column("sensitivity_time_seconds", sa.Float(), nullable=True),
        sa.Column("reference_url", sa.String(), nullable=True),
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("instrument", sa.Column("type", sa.String(length=50), nullable=True))
    op.add_column("instrument", sa.Column("reference_url", sa.String(), nullable=True))
    op.add_column(
        "instrument",
        sa.Column(
            "is_operational", sa.Boolean(), nullable=False, server_default="True"
        ),
    )
    op.add_column("observatory", sa.Column("reference_url", sa.String(), nullable=True))
    op.add_column(
        "observatory",
        sa.Column(
            "is_operational", sa.Boolean(), nullable=False, server_default="True"
        ),
    )
    op.add_column("telescope", sa.Column("reference_url", sa.String(), nullable=True))
    op.add_column(
        "telescope",
        sa.Column(
            "is_operational", sa.Boolean(), nullable=False, server_default="True"
        ),
    )
    # ### end Alembic commands ###

    # Add additional metadata to TESS observatory package
    bind = op.get_bind()
    session = orm.Session(bind=bind, expire_on_commit=False)
    stmt = select(Observatory).where(Observatory.short_name == "TESS")
    tess = session.execute(stmt).scalar_one_or_none()

    if tess is None:
        raise ValueError("TESS observatory not found")

    tess.reference_url = OBSERVATORY["reference_url"]  # type: ignore
    tess.telescopes[0].instruments[0].type = OBSERVATORY["telescopes"][0][
        "instruments"
    ][0]["type"]  # type: ignore

    # Commit the changes
    session.commit()
    session.close()

    op.alter_column("instrument", "type", nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telescope", "is_operational")
    op.drop_column("telescope", "reference_url")
    op.drop_column("observatory", "is_operational")
    op.drop_column("observatory", "reference_url")
    op.drop_column("instrument", "is_operational")
    op.drop_column("instrument", "reference_url")
    op.drop_column("instrument", "type")
    op.drop_table("filter")
    # ### end Alembic commands ###
