"""Add Ephemeris types and parameters

Revision ID: f1576fb297ac
Revises: 3df02ad6028d
Create Date: 2025-03-20 13:35:54.764017

"""

from enum import Enum
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from migrations.versions.model_snapshots.models_2025_03_20 import (
    Observatory,
    ObservatoryEphemerisParameters,
    ObservatoryEphemerisType,
)

# revision identifiers, used by Alembic.
revision: str = "f1576fb297ac"
down_revision: Union[str, None] = "3df02ad6028d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


class EphemerisType(str, Enum):
    TLE = "tle"
    SPICE = "spice"
    JPL = "jpl"
    GROUND = "ground"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "observatory_ephemeris_parameters",
        sa.Column("observatory_id", sa.UUID(), nullable=False),
        sa.Column("norad_id", sa.Integer(), nullable=True),
        sa.Column("norad_satellite_name", sa.String(length=69), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("height", sa.Float(), nullable=True),
        sa.Column("naif_id", sa.Integer(), nullable=True),
        sa.Column("spice_kernel_url", sa.String(length=256), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "\n            (longitude IS NULL AND latitude IS NULL AND height IS NULL) OR\n            (longitude IS NOT NULL AND latitude IS NOT NULL AND height IS NOT NULL)\n            ",
            name="ck_coordinates_all_or_none",
        ),
        sa.ForeignKeyConstraint(
            ["observatory_id"],
            ["observatory.id"],
        ),
        sa.PrimaryKeyConstraint("observatory_id", "id"),
        sa.UniqueConstraint("observatory_id", name="uq_observatory_id"),
    )
    op.create_table(
        "observatory_ephemeris_type",
        sa.Column("observatory_id", sa.UUID(), nullable=False),
        sa.Column("ephemeris_type", sa.String(length=10), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["observatory_id"],
            ["observatory.id"],
        ),
        sa.PrimaryKeyConstraint("observatory_id", "ephemeris_type", "id"),
        sa.UniqueConstraint(
            "observatory_id",
            "ephemeris_type",
            "priority",
            name="uq_observatory_type_priority",
        ),
    )

    tess = (
        op.get_bind()
        .execute(sa.select(Observatory.id).where(Observatory.short_name == "TESS"))
        .scalar_one()
    )

    # Add TESS ephemeris types and parameters
    op.get_bind().execute(
        sa.insert(ObservatoryEphemerisType).values(
            observatory_id=tess,
            ephemeris_type=EphemerisType.TLE,
            priority=1,
        )
    )
    op.get_bind().execute(
        sa.insert(ObservatoryEphemerisType).values(
            observatory_id=tess,
            ephemeris_type=EphemerisType.JPL,
            priority=2,
        )
    )
    op.get_bind().execute(
        sa.insert(ObservatoryEphemerisParameters).values(
            norad_satellite_name="TESS",
            norad_id=43435,
            longitude=None,
            latitude=None,
            height=None,
            naif_id=-95,
            spice_kernel_url=None,
            observatory_id=tess,
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("observatory_ephemeris_type")
    op.drop_table("observatory_ephemeris_parameters")
    # ### end Alembic commands ###
