"""Schedule table updates

Revision ID: 3245c430ace2
Revises: 593643a8ac92
Create Date: 2025-03-03 10:24:31.321076

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3245c430ace2"
down_revision: Union[str, None] = "593643a8ac92"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("schedule", sa.Column("telescope_id", sa.UUID(), nullable=False))
    op.add_column(
        "schedule", sa.Column("date_range_begin", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "schedule", sa.Column("date_range_end", sa.DateTime(), nullable=False)
    )
    op.add_column("schedule", sa.Column("status", sa.String(length=50), nullable=False))
    op.add_column(
        "schedule", sa.Column("external_id", sa.String(length=256), nullable=True)
    )
    op.add_column("schedule", sa.Column("name", sa.String(length=256), nullable=False))
    op.add_column(
        "schedule", sa.Column("fidelity", sa.String(length=50), nullable=False)
    )
    op.add_column(
        "schedule", sa.Column("checksum", sa.String(length=128), nullable=False)
    )
    op.drop_constraint("schedule_instrument_id_fkey", "schedule", type_="foreignkey")
    op.create_foreign_key(None, "schedule", "telescope", ["telescope_id"], ["id"])
    op.drop_column("schedule", "instrument_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedule",
        sa.Column("instrument_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "schedule_instrument_id_fkey",
        "schedule",
        "instrument",
        ["instrument_id"],
        ["id"],
    )
    op.drop_column("schedule", "checksum")
    op.drop_column("schedule", "fidelity")
    op.drop_column("schedule", "name")
    op.drop_column("schedule", "external_id")
    op.drop_column("schedule", "status")
    op.drop_column("schedule", "date_range_end")
    op.drop_column("schedule", "date_range_begin")
    op.drop_column("schedule", "telescope_id")
    # ### end Alembic commands ###
