"""Add Ephemeris Parameters and Types

Revision ID: 438a1fe7c75c
Revises: 3df02ad6028d
Create Date: 2025-04-05 13:23:58.047576

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import orm, select
from sqlalchemy.dialects import postgresql

from across_server.core.enums.ephemeris_type import EphemerisType
from migrations.versions.model_snapshots.models_2025_04_05 import (
    JPLEphemerisParameters,
    Observatory,
    ObservatoryEphemerisType,
    TLEParameters,
)

# revision identifiers, used by Alembic.
revision: str = "438a1fe7c75c"
down_revision: Union[str, None] = "3df02ad6028d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "earth_location_parameters",
        sa.Column("observatory_id", sa.UUID(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("height", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("observatory_id", "id"),
    )
    op.create_table(
        "jpl_ephemeris_parameters",
        sa.Column("observatory_id", sa.UUID(), nullable=False),
        sa.Column("naif_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("observatory_id", "id"),
        sa.UniqueConstraint(
            "naif_id", "observatory_id", name="uq_naif_id_observatory_id"
        ),
    )
    op.create_table(
        "observatory_ephemeris_type",
        sa.Column("observatory_id", sa.UUID(), nullable=False),
        sa.Column("ephemeris_type", sa.String(length=10), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["observatory_id"],
            ["observatory.id"],
        ),
        sa.PrimaryKeyConstraint("observatory_id", "ephemeris_type", "id"),
        sa.UniqueConstraint(
            "observatory_id",
            "ephemeris_type",
            "priority",
            name="uq_observatory_type_priority",
        ),
    )
    op.create_table(
        "spice_kernel_parameters",
        sa.Column("observatory_id", sa.UUID(), nullable=False),
        sa.Column("naif_id", sa.Integer(), nullable=False),
        sa.Column("spice_kernel_url", sa.String(length=256), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("observatory_id", "id"),
    )
    op.create_table(
        "tle_parameters",
        sa.Column("observatory_id", sa.UUID(), nullable=False),
        sa.Column("norad_id", sa.Integer(), nullable=False),
        sa.Column("norad_satellite_name", sa.String(length=69), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("observatory_id", "id"),
        sa.UniqueConstraint(
            "norad_id", "observatory_id", name="uq_norad_id_observatory_id"
        ),
    )

    op.alter_column(
        "observatory",
        "observatory_type",
        new_column_name="type",
        existing_type=postgresql.ENUM(
            "SPACE_BASED", "GROUND_BASED", name="observatory_type"
        ),
        existing_nullable=False,
    )

    # Add ObservatoryEphemerisType records for TESS
    bind = op.get_bind()
    session = orm.Session(bind=bind, expire_on_commit=False)
    stmt = select(Observatory.id).where(Observatory.short_name == "TESS")
    tess_id = session.execute(stmt).scalar_one_or_none()

    if tess_id is None:
        raise ValueError("TESS observatory not found")

    ephemeris_types = [
        ObservatoryEphemerisType(
            observatory_id=tess_id,
            ephemeris_type=EphemerisType.JPL,
            priority=1,
        ),
        ObservatoryEphemerisType(
            observatory_id=tess_id,
            ephemeris_type=EphemerisType.TLE,
            priority=2,
        ),
    ]
    session.add_all(ephemeris_types)

    # Add TLEParameters for TESS
    tle_parameters = TLEParameters(
        observatory_id=tess_id,
        norad_id=43435,
        norad_satellite_name="TESS",
    )
    session.add(tle_parameters)

    # Add JPLEphemerisParameters for TESS
    jpl_parameters = JPLEphemerisParameters(
        observatory_id=tess_id,
        naif_id=-95,
    )
    session.add(jpl_parameters)

    # Commit the changes
    session.commit()
    session.close()

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "observatory",
        "type",
        new_column_name="observatory_type",
        existing_type=postgresql.ENUM(
            "SPACE_BASED", "GROUND_BASED", name="observatory_type"
        ),
        existing_nullable=False,
    )

    op.drop_table("tle_parameters")
    op.drop_table("spice_kernel_parameters")
    op.drop_table("observatory_ephemeris_type")
    op.drop_table("jpl_ephemeris_parameters")
    op.drop_table("earth_location_parameters")
    # ### end Alembic commands ###
