"""some old bullshit

Revision ID: 34a2b65ed359
Revises: 65a3b3edae84
Create Date: 2025-04-07 10:16:34.301181

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision: str = "34a2b65ed359"
down_revision: Union[str, None] = "3df02ad6028d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "observation",
        "pointing_ra",
        new_column_name="pointing_position__ra",
        type_=sa.Float(precision=5),
        nullable=False,
    )
    op.alter_column(
        "observation",
        "pointing_dec",
        new_column_name="pointing_position__dec",
        type_=sa.Float(precision=5),
        nullable=False,
    )
    op.alter_column(
        "observation",
        "pointing_position",
        new_column_name="pointing_position_position",
        type_=Geography(
            geometry_type="POINT",
            srid=4326,
            from_text="ST_GeogFromText",
            name="geography",
            nullable=False,
        ),
    )
    op.alter_column(
        "observation",
        "object_ra",
        new_column_name="object_position__ra",
        type_=sa.Float(precision=5),
        nullable=True,
    )
    op.alter_column(
        "observation",
        "object_dec",
        new_column_name="object_position__dec",
        type_=sa.Float(precision=5),
        nullable=True,
    )
    op.alter_column(
        "observation",
        "object_position",
        new_column_name="object_position__position",
        type_=Geography(
            geometry_type="POINT",
            srid=4326,
            from_text="ST_GeogFromText",
            name="geography",
        ),
    )
    op.alter_column(
        "observation",
        "central_wavelength",
        new_column_name="bandpass__central_wavelength",
        type_=sa.Float(precision=2),
        nullable=True,
    )
    op.alter_column(
        "observation",
        "bandwidth",
        new_column_name="bandpass__bandwidth",
        type_=sa.Float(precision=2),
        nullable=True,
    )
    op.alter_column(
        "observation",
        "depth_unit",
        new_column_name="depth__unit",
        type_=sa.String(length=50),
        nullable=True,
    )
    op.alter_column(
        "observation",
        "depth_value",
        new_column_name="depth__value",
        type_=sa.Float(precision=2),
        nullable=True,
    )

    op.drop_index(
        "idx_observation_object_position",
        table_name="observation",
        postgresql_using="gist",
    )
    op.drop_index(
        "idx_observation_pointing_position",
        table_name="observation",
        postgresql_using="gist",
    )
    op.create_index(
        "idx_observation_object_position__position",
        "observation",
        ["object_position__position"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        "idx_observation_pointing_position__position",
        "observation",
        ["pointing_position_position"],
        unique=False,
        postgresql_using="gist",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "observation",
        "pointing_position_ra",
        new_column_name="pointing_ra",
        type_=sa.REAL(),
        nullable=False,
    )
    op.alter_column(
        "observation",
        "pointing_position_dec",
        new_column_name="pointing_dec",
        type_=sa.REAL(),
        nullable=False,
    )
    op.alter_column(
        "observation",
        "pointing_position_position",
        new_column_name="pointing_position",
        type_=Geography(
            geometry_type="POINT",
            srid=4326,
            from_text="ST_GeogFromText",
            name="geography",
            nullable=False,
        ),
    )
    op.alter_column(
        "observation",
        "object_position_ra",
        new_column_name="object_ra",
        type_=sa.REAL(),
        nullable=True,
    )
    op.alter_column(
        "observation",
        "object_position_dec",
        new_column_name="object_dec",
        type_=sa.REAL(),
        nullable=True,
    )
    op.alter_column(
        "observation",
        "object_position_position",
        new_column_name="object_position",
        type_=Geography(
            geometry_type="POINT",
            srid=4326,
            from_text="ST_GeogFromText",
            name="geography",
        ),
    )
    op.alter_column(
        "observation",
        "bandpass_central_wavelength",
        new_column_name="central_wavelength",
        type_=sa.REAL(),
        nullable=True,
    )
    op.alter_column(
        "observation",
        "bandpass_bandwidth",
        new_column_name="bandwidth",
        type_=sa.REAL(),
        nullable=True,
    )
    op.drop_index(
        "idx_observation_pointing_position_position",
        table_name="observation",
        postgresql_using="gist",
    )
    op.drop_index(
        "idx_observation_object_position_position",
        table_name="observation",
        postgresql_using="gist",
    )
    op.create_index(
        "idx_observation_pointing_position",
        "observation",
        ["pointing_position"],
        unique=False,
        postgresql_using="gist",
    )
    op.create_index(
        "idx_observation_object_position",
        "observation",
        ["object_position"],
        unique=False,
        postgresql_using="gist",
    )
    # ### end Alembic commands ###
