"""service account group roles

Revision ID: 3df02ad6028d
Revises: 3245c430ace2
Create Date: 2025-03-07 15:28:39.513808

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3df02ad6028d"
down_revision: Union[str, None] = "3245c430ace2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_account_group_role",
        sa.Column("service_account_id", sa.UUID(), nullable=False),
        sa.Column("group_role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_role_id"],
            ["group_role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_account_id"],
            ["service_account.id"],
        ),
        sa.PrimaryKeyConstraint("service_account_id", "group_role_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("service_account_group_role")
    # ### end Alembic commands ###
