"""init

Revision ID: ed3a08dbfcc0
Revises:
Create Date: 2025-04-23 15:49:48.467984

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision: str = "ed3a08dbfcc0"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "earth_location_parameters",
        sa.Column("observatory_id", sa.UUID(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("height", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("observatory_id", "id"),
        schema="across",
    )
    op.create_table(
        "group",
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("short_name", sa.String(length=25), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="across",
    )
    op.create_index(
        op.f("ix_across_group_short_name"),
        "group",
        ["short_name"],
        unique=False,
        schema="across",
    )
    op.create_table(
        "jpl_ephemeris_parameters",
        sa.Column("observatory_id", sa.UUID(), nullable=False),
        sa.Column("naif_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("observatory_id", "id"),
        sa.UniqueConstraint(
            "naif_id", "observatory_id", name="uq_naif_id_observatory_id"
        ),
        schema="across",
    )
    op.create_table(
        "observatory",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("short_name", sa.String(length=50), nullable=True),
        sa.Column("type", sa.String(length=25), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="across",
    )
    op.create_table(
        "permission",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="across",
    )
    op.create_index(
        op.f("ix_across_permission_name"),
        "permission",
        ["name"],
        unique=True,
        schema="across",
    )
    op.create_table(
        "role",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="across",
    )
    op.create_table(
        "spice_kernel_parameters",
        sa.Column("observatory_id", sa.UUID(), nullable=False),
        sa.Column("naif_id", sa.Integer(), nullable=False),
        sa.Column("spice_kernel_url", sa.String(length=256), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("observatory_id", "id"),
        schema="across",
    )
    op.create_table(
        "tle",
        sa.Column("norad_id", sa.Integer(), nullable=False),
        sa.Column("epoch", sa.DateTime(), nullable=False),
        sa.Column("satellite_name", sa.String(length=69), nullable=False),
        sa.Column("tle1", sa.String(length=69), nullable=False),
        sa.Column("tle2", sa.String(length=69), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("norad_id", "epoch", "id"),
        sa.UniqueConstraint("epoch", "norad_id", name="uq_epoch_norad_id"),
        schema="across",
    )
    op.create_table(
        "tle_parameters",
        sa.Column("observatory_id", sa.UUID(), nullable=False),
        sa.Column("norad_id", sa.Integer(), nullable=False),
        sa.Column("norad_satellite_name", sa.String(length=69), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("observatory_id", "id"),
        sa.UniqueConstraint(
            "norad_id", "observatory_id", name="uq_norad_id_observatory_id"
        ),
        schema="across",
    )
    op.create_table(
        "user",
        sa.Column("username", sa.String(length=25), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="across",
    )
    op.create_index(
        op.f("ix_across_user_email"), "user", ["email"], unique=True, schema="across"
    )
    op.create_index(
        op.f("ix_across_user_username"),
        "user",
        ["username"],
        unique=False,
        schema="across",
    )
    op.create_table(
        "group_invite",
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("receiver_email", sa.String(length=100), nullable=False),
        sa.Column("receiver_id", sa.UUID(), nullable=True),
        sa.Column("sender_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["across.group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["receiver_id"],
            ["across.user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["across.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="across",
    )
    op.create_table(
        "group_observatory",
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("observatory_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["across.group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["observatory_id"],
            ["across.observatory.id"],
        ),
        sa.PrimaryKeyConstraint("group_id", "observatory_id"),
        schema="across",
    )
    op.create_table(
        "group_role",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["across.group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="across",
    )
    op.create_table(
        "observatory_ephemeris_type",
        sa.Column("observatory_id", sa.UUID(), nullable=False),
        sa.Column("ephemeris_type", sa.String(length=10), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["observatory_id"],
            ["across.observatory.id"],
        ),
        sa.PrimaryKeyConstraint("observatory_id", "ephemeris_type", "id"),
        sa.UniqueConstraint(
            "observatory_id",
            "ephemeris_type",
            "priority",
            name="uq_observatory_type_priority",
        ),
        schema="across",
    )
    op.create_table(
        "role_permission",
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["across.permission.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["across.role.id"],
        ),
        sa.PrimaryKeyConstraint("permission_id", "role_id"),
        schema="across",
    )
    op.create_table(
        "service_account",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("expiration", sa.DateTime(), nullable=False),
        sa.Column("expiration_duration", sa.Integer(), nullable=False),
        sa.Column("secret_key", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["across.user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="across",
    )
    op.create_table(
        "telescope",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("short_name", sa.String(length=50), nullable=True),
        sa.Column("observatory_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["observatory_id"],
            ["across.observatory.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="across",
    )
    op.create_table(
        "user_group",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["across.group.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["across.user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "group_id"),
        schema="across",
    )
    op.create_table(
        "user_role",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["across.role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["across.user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
        schema="across",
    )
    op.create_table(
        "group_role_permission",
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.Column("group_role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_role_id"],
            ["across.group_role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["across.permission.id"],
        ),
        sa.PrimaryKeyConstraint("permission_id", "group_role_id"),
        schema="across",
    )
    op.create_table(
        "instrument",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("short_name", sa.String(length=50), nullable=True),
        sa.Column("telescope_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["telescope_id"],
            ["across.telescope.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="across",
    )
    op.create_table(
        "schedule",
        sa.Column("telescope_id", sa.UUID(), nullable=False),
        sa.Column("date_range_begin", sa.DateTime(), nullable=False),
        sa.Column("date_range_end", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("external_id", sa.String(length=256), nullable=True),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("fidelity", sa.String(length=50), nullable=False),
        sa.Column("checksum", sa.String(length=128), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["telescope_id"],
            ["across.telescope.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="across",
    )
    op.create_table(
        "service_account_group_role",
        sa.Column("service_account_id", sa.UUID(), nullable=False),
        sa.Column("group_role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_role_id"],
            ["across.group_role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_account_id"],
            ["across.service_account.id"],
        ),
        sa.PrimaryKeyConstraint("service_account_id", "group_role_id"),
        schema="across",
    )
    op.create_table(
        "service_account_role",
        sa.Column("service_account_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["across.role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_account_id"],
            ["across.service_account.id"],
        ),
        sa.PrimaryKeyConstraint("service_account_id", "role_id"),
        schema="across",
    )
    op.create_table(
        "user_group_role",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("group_role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_role_id"],
            ["across.group_role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["across.user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "group_role_id"),
        schema="across",
    )
    op.create_table(
        "footprint",
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column(
            "polygon",
            Geography(
                geometry_type="POLYGON",
                srid=4326,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["across.instrument.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="across",
    )
    op.create_table(
        "observation",
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("schedule_id", sa.UUID(), nullable=False),
        sa.Column("object_name", sa.String(length=100), nullable=False),
        sa.Column("pointing_ra", sa.Float(precision=5), nullable=False),
        sa.Column("pointing_dec", sa.Float(precision=5), nullable=False),
        sa.Column(
            "pointing_position",
            Geography(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("date_range_begin", sa.DateTime(), nullable=False),
        sa.Column("date_range_end", sa.DateTime(), nullable=False),
        sa.Column("external_observation_id", sa.String(length=50), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("exposure_time", sa.Float(precision=2), nullable=True),
        sa.Column("reason", sa.String(length=100), nullable=True),
        sa.Column("description", sa.String(length=100), nullable=True),
        sa.Column("proposal_reference", sa.String(length=100), nullable=True),
        sa.Column("object_ra", sa.Float(precision=5), nullable=True),
        sa.Column("object_dec", sa.Float(precision=5), nullable=True),
        sa.Column(
            "object_position",
            Geography(
                geometry_type="POINT",
                srid=4326,
                from_text="ST_GeogFromText",
                name="geography",
            ),
            nullable=True,
        ),
        sa.Column("pointing_angle", sa.Float(), nullable=True),
        sa.Column("depth_value", sa.Float(precision=2), nullable=True),
        sa.Column("depth_unit", sa.String(length=50), nullable=True),
        sa.Column("central_wavelength", sa.Float(precision=2), nullable=True),
        sa.Column("bandwidth", sa.Float(precision=2), nullable=True),
        sa.Column("filter_name", sa.String(length=50), nullable=True),
        sa.Column("t_resolution", sa.Float(), nullable=True),
        sa.Column("em_res_power", sa.Float(), nullable=True),
        sa.Column("o_ucd", sa.String(), nullable=True),
        sa.Column("pol_states", sa.String(), nullable=True),
        sa.Column("pol_xel", sa.String(), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("tracking_type", sa.String(length=50), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["across.instrument.id"],
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["across.schedule.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="across",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("observation", schema="across")
    op.drop_table("footprint", schema="across")
    op.drop_table("user_group_role", schema="across")
    op.drop_table("service_account_role", schema="across")
    op.drop_table("service_account_group_role", schema="across")
    op.drop_table("schedule", schema="across")
    op.drop_table("instrument", schema="across")
    op.drop_table("group_role_permission", schema="across")
    op.drop_table("user_role", schema="across")
    op.drop_table("user_group", schema="across")
    op.drop_table("telescope", schema="across")
    op.drop_table("service_account", schema="across")
    op.drop_table("role_permission", schema="across")
    op.drop_table("observatory_ephemeris_type", schema="across")
    op.drop_table("group_role", schema="across")
    op.drop_table("group_observatory", schema="across")
    op.drop_table("group_invite", schema="across")
    op.drop_index(op.f("ix_across_user_username"), table_name="user", schema="across")
    op.drop_index(op.f("ix_across_user_email"), table_name="user", schema="across")
    op.drop_table("user", schema="across")
    op.drop_table("tle_parameters", schema="across")
    op.drop_table("tle", schema="across")
    op.drop_table("spice_kernel_parameters", schema="across")
    op.drop_table("role", schema="across")
    op.drop_index(
        op.f("ix_across_permission_name"), table_name="permission", schema="across"
    )
    op.drop_table("permission", schema="across")
    op.drop_table("observatory", schema="across")
    op.drop_table("jpl_ephemeris_parameters", schema="across")
    op.drop_index(
        op.f("ix_across_group_short_name"), table_name="group", schema="across"
    )
    op.drop_table("group", schema="across")
    op.drop_table("earth_location_parameters", schema="across")
    # ### end Alembic commands ###
