"""bandpass to min/max wavelength

Revision ID: a0d523f8883b
Revises: 3df02ad6028d
Create Date: 2025-04-15 15:32:01.874040

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a0d523f8883b"
down_revision: Union[str, None] = "3df02ad6028d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "observation",
        sa.Column("peak_wavelength", sa.Float(precision=2), nullable=True),
    )
    op.add_column(
        "observation", sa.Column("max_wavelength", sa.Float(precision=2), nullable=True)
    )
    op.add_column(
        "observation", sa.Column("min_wavelength", sa.Float(precision=2), nullable=True)
    )
    op.drop_column("observation", "central_wavelength")
    op.drop_column("observation", "bandwidth")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "observation",
        sa.Column("bandwidth", sa.REAL(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "observation",
        sa.Column("central_wavelength", sa.REAL(), autoincrement=False, nullable=True),
    )
    op.drop_column("observation", "min_wavelength")
    op.drop_column("observation", "max_wavelength")
    op.drop_column("observation", "peak_wavelength")
    # ### end Alembic commands ###
