"""Service Accounts

Revision ID: 818523f50d93
Revises: c5361765767a
Create Date: 2025-01-13 16:20:21.233671

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "818523f50d93"
down_revision: Union[str, None] = "c5361765767a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_account",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("expiration", sa.DateTime(), nullable=False),
        sa.Column("expiration_duration", sa.Integer(), nullable=False),
        sa.Column("secret_key", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "service_account_role",
        sa.Column("service_account_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_account_id"],
            ["service_account.id"],
        ),
        sa.PrimaryKeyConstraint("service_account_id", "role_id"),
    )
    op.drop_constraint("footprint_created_by_id_fkey", "footprint", type_="foreignkey")
    op.drop_constraint("footprint_modified_by_id_fkey", "footprint", type_="foreignkey")
    op.drop_constraint("group_created_by_id_fkey", "group", type_="foreignkey")
    op.drop_constraint("group_modified_by_id_fkey", "group", type_="foreignkey")
    op.drop_constraint(
        "group_invite_created_by_id_fkey", "group_invite", type_="foreignkey"
    )
    op.drop_constraint(
        "group_invite_modified_by_id_fkey", "group_invite", type_="foreignkey"
    )
    op.drop_constraint(
        "group_role_modified_by_id_fkey", "group_role", type_="foreignkey"
    )
    op.drop_constraint(
        "group_role_created_by_id_fkey", "group_role", type_="foreignkey"
    )
    op.drop_constraint(
        "instrument_created_by_id_fkey", "instrument", type_="foreignkey"
    )
    op.drop_constraint(
        "instrument_modified_by_id_fkey", "instrument", type_="foreignkey"
    )
    op.drop_constraint(
        "observation_modified_by_id_fkey", "observation", type_="foreignkey"
    )
    op.drop_constraint(
        "observation_created_by_id_fkey", "observation", type_="foreignkey"
    )
    op.drop_constraint(
        "observatory_created_by_id_fkey", "observatory", type_="foreignkey"
    )
    op.drop_constraint(
        "observatory_modified_by_id_fkey", "observatory", type_="foreignkey"
    )
    op.drop_constraint(
        "permission_created_by_id_fkey", "permission", type_="foreignkey"
    )
    op.drop_constraint("role_created_by_id_fkey", "role", type_="foreignkey")
    op.drop_constraint("role_modified_by_id_fkey", "role", type_="foreignkey")
    op.drop_constraint("schedule_modified_by_id_fkey", "schedule", type_="foreignkey")
    op.drop_constraint("schedule_created_by_id_fkey", "schedule", type_="foreignkey")
    op.drop_constraint("telescope_modified_by_id_fkey", "telescope", type_="foreignkey")
    op.drop_constraint("telescope_created_by_id_fkey", "telescope", type_="foreignkey")
    op.drop_constraint("user_modified_by_id_fkey", "user", type_="foreignkey")
    op.drop_constraint("user_created_by_id_fkey", "user", type_="foreignkey")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "user_created_by_id_fkey", "user", "user", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        "user_modified_by_id_fkey", "user", "user", ["modified_by_id"], ["id"]
    )
    op.create_foreign_key(
        "telescope_created_by_id_fkey", "telescope", "user", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        "telescope_modified_by_id_fkey", "telescope", "user", ["modified_by_id"], ["id"]
    )
    op.create_foreign_key(
        "schedule_created_by_id_fkey", "schedule", "user", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        "schedule_modified_by_id_fkey", "schedule", "user", ["modified_by_id"], ["id"]
    )
    op.create_foreign_key(
        "role_modified_by_id_fkey", "role", "user", ["modified_by_id"], ["id"]
    )
    op.create_foreign_key(
        "role_created_by_id_fkey", "role", "user", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        "permission_created_by_id_fkey", "permission", "user", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        "observatory_modified_by_id_fkey",
        "observatory",
        "user",
        ["modified_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        "observatory_created_by_id_fkey",
        "observatory",
        "user",
        ["created_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        "observation_created_by_id_fkey",
        "observation",
        "user",
        ["created_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        "observation_modified_by_id_fkey",
        "observation",
        "user",
        ["modified_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        "instrument_modified_by_id_fkey",
        "instrument",
        "user",
        ["modified_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        "instrument_created_by_id_fkey", "instrument", "user", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        "group_role_created_by_id_fkey", "group_role", "user", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        "group_role_modified_by_id_fkey",
        "group_role",
        "user",
        ["modified_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        "group_invite_modified_by_id_fkey",
        "group_invite",
        "user",
        ["modified_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        "group_invite_created_by_id_fkey",
        "group_invite",
        "user",
        ["created_by_id"],
        ["id"],
    )
    op.create_foreign_key(
        "group_modified_by_id_fkey", "group", "user", ["modified_by_id"], ["id"]
    )
    op.create_foreign_key(
        "group_created_by_id_fkey", "group", "user", ["created_by_id"], ["id"]
    )
    op.create_foreign_key(
        "footprint_modified_by_id_fkey", "footprint", "user", ["modified_by_id"], ["id"]
    )
    op.create_foreign_key(
        "footprint_created_by_id_fkey", "footprint", "user", ["created_by_id"], ["id"]
    )
    op.drop_table("service_account_role")
    op.drop_table("service_account")
    # ### end Alembic commands ###
