"""add tle table

Revision ID: 593643a8ac92
Revises: 818523f50d93
Create Date: 2025-02-08 07:51:44.156033

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "593643a8ac92"
down_revision: Union[str, None] = "818523f50d93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tle",
        sa.Column("norad_id", sa.Integer(), nullable=False, primary_key=True),
        sa.Column("epoch", sa.DateTime(), nullable=False, primary_key=True),
        sa.Column("satellite_name", sa.String(length=69), nullable=False),
        sa.Column("tle1", sa.String(length=69), nullable=False),
        sa.Column("tle2", sa.String(length=69), nullable=False),
        sa.PrimaryKeyConstraint("norad_id", "epoch"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tle")
    # ### end Alembic commands ###
