"""add instrument metadata parameters

Revision ID: 0f2036717762
Revises: e4ec21aebc19
Create Date: 2025-04-23 12:48:30.301710

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f2036717762"
down_revision: Union[str, None] = "e4ec21aebc19"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "filter",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("peak_wavelength", sa.Float(), nullable=True),
        sa.Column("min_wavelength", sa.Float(), nullable=False),
        sa.Column("max_wavelength", sa.Float(), nullable=False),
        sa.Column(
            "is_operational", sa.Boolean(), nullable=False, server_default="True"
        ),
        sa.Column("sensitivity_depth_unit", sa.String(length=50), nullable=True),
        sa.Column("sensitivity_depth", sa.Float(), nullable=True),
        sa.Column("sensitivity_time_seconds", sa.Float(), nullable=True),
        sa.Column("reference_url", sa.String(), nullable=True),
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["across.instrument.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="across",
    )
    op.add_column(
        "instrument",
        sa.Column("type", sa.String(length=50), nullable=False),
        schema="across",
    )
    op.add_column(
        "instrument",
        sa.Column("reference_url", sa.String(), nullable=True),
        schema="across",
    )
    op.add_column(
        "instrument",
        sa.Column(
            "is_operational", sa.Boolean(), nullable=False, server_default="True"
        ),
        schema="across",
    )
    op.add_column(
        "observatory",
        sa.Column("reference_url", sa.String(), nullable=True),
        schema="across",
    )
    op.add_column(
        "observatory",
        sa.Column(
            "is_operational", sa.Boolean(), nullable=False, server_default="True"
        ),
        schema="across",
    )
    op.add_column(
        "telescope",
        sa.Column("reference_url", sa.String(), nullable=True),
        schema="across",
    )
    op.add_column(
        "telescope",
        sa.Column(
            "is_operational", sa.Boolean(), nullable=False, server_default="True"
        ),
        schema="across",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telescope", "is_operational", schema="across")
    op.drop_column("telescope", "reference_url", schema="across")
    op.drop_column("observatory", "is_operational", schema="across")
    op.drop_column("observatory", "reference_url", schema="across")
    op.drop_column("instrument", "is_operational", schema="across")
    op.drop_column("instrument", "reference_url", schema="across")
    op.drop_column("instrument", "type", schema="across")
    op.drop_table("filter", schema="across")
    # ### end Alembic commands ###
