"""no no

Revision ID: 0b1bb8c35116
Revises: 50c390eb41cb
Create Date: 2025-07-02 16:31:57.812927

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0b1bb8c35116"
down_revision: Union[str, None] = "50c390eb41cb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "instrument",
        sa.Column("visibility_type", sa.String(length=10), nullable=True),
        schema="across",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("instrument", "visibility_type", schema="across")
    # ### end Alembic commands ###
