"""service_account_hashed_key_and_salt

Revision ID: 3809d4ab4e06
Revises: 2b00546497c1
Create Date: 2025-05-28 11:55:55.891252

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3809d4ab4e06"
down_revision: Union[str, None] = "2b00546497c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "service_account", "secret_key", new_column_name="hashed_key", schema="across"
    )
    op.add_column(
        "service_account",
        sa.Column("salt", sa.String(), nullable=False),
        schema="across",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "service_account", "hashed_key", new_column_name="secret_key", schema="across"
    )
    op.drop_column("service_account", "salt", schema="across")
    # ### end Alembic commands ###
