"""Fix norad_satellite_id for Swift

Revision ID: d5c4e2fc57bc
Revises: 2c08825167f4
Create Date: 2025-08-02 10:23:21.312640

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy import update
from sqlalchemy.orm import sessionmaker

from migrations.versions.model_snapshots.models_2025_06_18 import TLEParameters

# revision identifiers, used by Alembic.
revision: str = "d5c4e2fc57bc"
down_revision: Union[str, None] = "2c08825167f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()

    Session = sessionmaker(bind=connection)
    session = Session()

    try:
        session.execute(
            update(TLEParameters)
            .where(TLEParameters.norad_id == 28485)
            .values(norad_satellite_name="SWIFT")
        )
        session.commit()
    finally:
        session.close()

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()

    Session = sessionmaker(bind=connection)
    session = Session()

    try:
        session.execute(
            update(TLEParameters)
            .where(TLEParameters.norad_id == 28485)
            .values(norad_satellite_name="Swift")
        )
        session.commit()
    finally:
        session.close()
    # ### end Alembic commands ###
