"""adding observation request models

Revision ID: 6a81b90801ad
Revises: 43f24460b144
Create Date: 2026-05-26 13:47:37.611210

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geography
from sqlalchemy import orm, select

import migrations.versions.model_snapshots.models_2026_05_26 as models

# revision identifiers, used by Alembic.
revision: str = "6a81b90801ad"
down_revision: Union[str, None] = "43f24460b144"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_across_broker_alert_created_by_id"),
        "broker_alert",
        ["created_by_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        op.f("ix_across_broker_event_created_by_id"),
        "broker_event",
        ["created_by_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        op.f("ix_across_constraint_created_by_id"),
        "constraint",
        ["created_by_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        op.f("ix_across_earth_location_parameters_created_by_id"),
        "earth_location_parameters",
        ["created_by_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        op.f("ix_across_filter_created_by_id"),
        "filter",
        ["created_by_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        op.f("ix_across_footprint_created_by_id"),
        "footprint",
        ["created_by_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        op.f("ix_across_group_created_by_id"),
        "group",
        ["created_by_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        op.f("ix_across_group_invite_created_by_id"),
        "group_invite",
        ["created_by_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        op.f("ix_across_group_role_created_by_id"),
        "group_role",
        ["created_by_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        op.f("ix_across_instrument_created_by_id"),
        "instrument",
        ["created_by_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        op.f("ix_across_jpl_ephemeris_parameters_created_by_id"),
        "jpl_ephemeris_parameters",
        ["created_by_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        op.f("ix_across_localization_created_by_id"),
        "localization",
        ["created_by_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        op.f("ix_across_observation_created_by_id"),
        "observation",
        ["created_by_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        op.f("ix_across_observatory_created_by_id"),
        "observatory",
        ["created_by_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        op.f("ix_across_permission_created_by_id"),
        "permission",
        ["created_by_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        op.f("ix_across_role_created_by_id"),
        "role",
        ["created_by_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        op.f("ix_across_schedule_created_by_id"),
        "schedule",
        ["created_by_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        op.f("ix_across_schedule_cadence_created_by_id"),
        "schedule_cadence",
        ["created_by_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        op.f("ix_across_service_account_created_by_id"),
        "service_account",
        ["created_by_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        op.f("ix_across_spice_kernel_parameters_created_by_id"),
        "spice_kernel_parameters",
        ["created_by_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        op.f("ix_across_telescope_created_by_id"),
        "telescope",
        ["created_by_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        op.f("ix_across_tle_parameters_created_by_id"),
        "tle_parameters",
        ["created_by_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        op.f("ix_across_user_created_by_id"),
        "user",
        ["created_by_id"],
        unique=False,
        schema="across",
    )
    op.create_table(
        "observing_proposal",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="across",
    )
    op.create_table(
        "observation_request",
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("status_reason", sa.String(), nullable=True),
        sa.Column("science_justification", sa.String(), nullable=False),
        sa.Column("object_ra", sa.Float(), nullable=False),
        sa.Column("object_dec", sa.Float(), nullable=False),
        sa.Column("object_position_error", sa.Float(), nullable=True),
        sa.Column("object_brightness", sa.Float(), nullable=False),
        sa.Column("object_brightness_unit", sa.String(length=25), nullable=False),
        sa.Column(
            "object_position",
            Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("object_name", sa.String(length=100), nullable=False),
        sa.Column("date_range_begin", sa.DateTime(), nullable=False),
        sa.Column("date_range_end", sa.DateTime(), nullable=True),
        sa.Column("exposure_time", sa.Float(), nullable=False),
        sa.Column("proposal_id", sa.UUID(), nullable=True),
        sa.Column("parent_id", sa.UUID(), nullable=False),
        sa.Column("anonymize", sa.Boolean(), nullable=False),
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("instrument_configuration", sa.JSON(), nullable=True),
        sa.Column("is_too", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["across.instrument.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["across.observation_request.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["across.observing_proposal.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="across",
    )
    op.create_index(
        "ix_across_observation_request_created_by_id",
        "observation_request",
        ["created_by_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        "ix_across_observation_request_date_range",
        "observation_request",
        ["date_range_begin", "date_range_end"],
        unique=False,
        schema="across",
    )
    op.create_index(
        "ix_across_observation_request_date_range_begin",
        "observation_request",
        ["date_range_begin"],
        unique=False,
        schema="across",
    )
    op.create_index(
        "ix_across_observation_request_date_range_end",
        "observation_request",
        ["date_range_end"],
        unique=False,
        schema="across",
    )
    op.create_index(
        "ix_across_observation_request_instrument_id",
        "observation_request",
        ["instrument_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        "ix_across_observation_request_object_position",
        "observation_request",
        ["object_position"],
        unique=False,
        schema="across",
        postgresql_using="gist",
    )
    op.create_index(
        "ix_across_observation_request_parent_id",
        "observation_request",
        ["parent_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        "ix_across_observation_request_proposal_id",
        "observation_request",
        ["proposal_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        "ix_across_observation_request_status",
        "observation_request",
        ["status"],
        unique=False,
        schema="across",
    )
    op.add_column(
        "instrument",
        sa.Column("is_observation_request_enabled", sa.Boolean(), nullable=True),
        schema="across",
    )
    op.add_column(
        "telescope",
        sa.Column("is_observation_request_enabled", sa.Boolean(), nullable=True),
        schema="across",
    )
    # ### end Alembic commands ###

    # Step 2: populate column with values
    bind = op.get_bind()
    session = orm.Session(bind=bind, expire_on_commit=False)

    telescopes = session.scalars(select(models.Telescope).with_for_update())
    for telescope in list(telescopes.all()):
        telescope.is_observation_request_enabled = False

    instruments = session.scalars(select(models.Instrument).with_for_update())
    for instrument in list(instruments.all()):
        instrument.is_observation_request_enabled = False
    session.commit()

    # Step 3: set column to not nullable.
    op.alter_column(
        table_name="telescope",
        column_name="is_observation_request_enabled",
        nullable=False,
        schema="across",
    )
    op.alter_column(
        table_name="instrument",
        column_name="is_observation_request_enabled",
        nullable=False,
        schema="across",
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telescope", "is_observation_request_enabled", schema="across")
    op.drop_column("instrument", "is_observation_request_enabled", schema="across")
    op.drop_index(
        "ix_across_observation_request_status",
        table_name="observation_request",
        schema="across",
    )
    op.drop_index(
        "ix_across_observation_request_proposal_id",
        table_name="observation_request",
        schema="across",
    )
    op.drop_index(
        "ix_across_observation_request_parent_id",
        table_name="observation_request",
        schema="across",
    )
    op.drop_index(
        "ix_across_observation_request_object_position",
        table_name="observation_request",
        schema="across",
        postgresql_using="gist",
    )
    op.drop_index(
        "ix_across_observation_request_instrument_id",
        table_name="observation_request",
        schema="across",
    )
    op.drop_index(
        "ix_across_observation_request_date_range_end",
        table_name="observation_request",
        schema="across",
    )
    op.drop_index(
        "ix_across_observation_request_date_range_begin",
        table_name="observation_request",
        schema="across",
    )
    op.drop_index(
        "ix_across_observation_request_date_range",
        table_name="observation_request",
        schema="across",
    )
    op.drop_index(
        "ix_across_observation_request_created_by_id",
        table_name="observation_request",
        schema="across",
    )
    op.drop_index(
        op.f("ix_across_user_created_by_id"), table_name="user", schema="across"
    )
    op.drop_index(
        op.f("ix_across_tle_parameters_created_by_id"),
        table_name="tle_parameters",
        schema="across",
    )
    op.drop_index(
        op.f("ix_across_telescope_created_by_id"),
        table_name="telescope",
        schema="across",
    )
    op.drop_index(
        op.f("ix_across_spice_kernel_parameters_created_by_id"),
        table_name="spice_kernel_parameters",
        schema="across",
    )
    op.drop_index(
        op.f("ix_across_service_account_created_by_id"),
        table_name="service_account",
        schema="across",
    )
    op.drop_index(
        op.f("ix_across_schedule_cadence_created_by_id"),
        table_name="schedule_cadence",
        schema="across",
    )
    op.drop_index(
        op.f("ix_across_schedule_created_by_id"), table_name="schedule", schema="across"
    )
    op.drop_index(
        op.f("ix_across_role_created_by_id"), table_name="role", schema="across"
    )
    op.drop_index(
        op.f("ix_across_permission_created_by_id"),
        table_name="permission",
        schema="across",
    )
    # op.drop_index(
    #     op.f("ix_across_observing_proposal_created_by_id"),
    #     table_name="observing_proposal",
    #     schema="across",
    # )
    op.drop_index(
        op.f("ix_across_observatory_created_by_id"),
        table_name="observatory",
        schema="across",
    )
    op.drop_index(
        op.f("ix_across_observation_created_by_id"),
        table_name="observation",
        schema="across",
    )
    op.drop_index(
        op.f("ix_across_localization_created_by_id"),
        table_name="localization",
        schema="across",
    )
    op.drop_index(
        op.f("ix_across_jpl_ephemeris_parameters_created_by_id"),
        table_name="jpl_ephemeris_parameters",
        schema="across",
    )
    op.drop_index(
        op.f("ix_across_instrument_created_by_id"),
        table_name="instrument",
        schema="across",
    )
    op.drop_index(
        op.f("ix_across_group_role_created_by_id"),
        table_name="group_role",
        schema="across",
    )
    op.drop_index(
        op.f("ix_across_group_invite_created_by_id"),
        table_name="group_invite",
        schema="across",
    )
    op.drop_index(
        op.f("ix_across_group_created_by_id"), table_name="group", schema="across"
    )
    op.drop_index(
        op.f("ix_across_footprint_created_by_id"),
        table_name="footprint",
        schema="across",
    )
    op.drop_index(
        op.f("ix_across_filter_created_by_id"), table_name="filter", schema="across"
    )
    op.drop_index(
        op.f("ix_across_earth_location_parameters_created_by_id"),
        table_name="earth_location_parameters",
        schema="across",
    )
    op.drop_index(
        op.f("ix_across_constraint_created_by_id"),
        table_name="constraint",
        schema="across",
    )
    op.drop_index(
        op.f("ix_across_broker_event_created_by_id"),
        table_name="broker_event",
        schema="across",
    )
    op.drop_index(
        op.f("ix_across_broker_alert_created_by_id"),
        table_name="broker_alert",
        schema="across",
    )
    op.drop_table("observation_request", schema="across")
    op.drop_table("observing_proposal", schema="across")
    # ### end Alembic commands ###
