"""add instrument constraints

Revision ID: 50c390eb41cb
Revises: d41e0c380a1f
Create Date: 2025-06-30 15:02:13.633687

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "50c390eb41cb"
down_revision: Union[str, None] = "0f1706aa008d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "constraint",
        sa.Column("constraint_type", sa.String(length=50), nullable=False),
        sa.Column("constraint_parameters", sa.JSON(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="across",
    )
    op.create_table(
        "instrument_constraint",
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("constraint_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["constraint_id"],
            ["across.constraint.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["across.instrument.id"],
        ),
        sa.PrimaryKeyConstraint("instrument_id", "constraint_id"),
        schema="across",
    )
    op.add_column(
        "instrument",
        sa.Column("visibility_type", sa.String(length=10), nullable=True),
        schema="across",
    )
    op.add_column(
        "observatory",
        sa.Column(
            "operational_begin_date",
            sa.DateTime(),
            nullable=True,
        ),
        schema="across",
    )
    op.add_column(
        "observatory",
        sa.Column("operational_end_date", sa.DateTime(), nullable=True),
        schema="across",
    )
    op.execute(
        "UPDATE across.observatory SET operational_begin_date = '1970-01-01 00:00:00'::timestamp"
    )
    op.alter_column(
        "observatory", "operational_begin_date", nullable=False, schema="across"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("observatory", "operational_end_date", schema="across")
    op.drop_column("observatory", "operational_begin_date", schema="across")
    op.drop_column("instrument", "visibility_type", schema="across")
    op.drop_table("instrument_constraint", schema="across")
    op.drop_table("constraint", schema="across")
    # ### end Alembic commands ###
