"""add instrument constraints

Revision ID: 50c390eb41cb
Revises: 59faf999b470
Create Date: 2025-06-30 15:02:13.633687

"""

import uuid
from typing import Sequence, Union

import sqlalchemy as sa
from across.tools.core.enums import ConstraintType
from across.tools.visibility.constraints import (
    EarthLimbConstraint,
    MoonAngleConstraint,
    SunAngleConstraint,
)
from alembic import op
from sqlalchemy import orm

import migrations.versions.model_snapshots.models_2025_10_03 as models
from across_server.core.enums.instrument_fov import InstrumentFOV
from across_server.core.enums.visibility_type import VisibilityType

# revision identifiers, used by Alembic.
revision: str = "50c390eb41cb"
down_revision: Union[str, None] = "59faf999b470"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "constraint",
        sa.Column("constraint_type", sa.String(length=50), nullable=False),
        sa.Column("constraint_parameters", sa.JSON(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="across",
    )
    op.create_table(
        "instrument_constraint",
        sa.Column("instrument_id", sa.UUID(), nullable=False),
        sa.Column("constraint_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["constraint_id"],
            ["across.constraint.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["across.instrument.id"],
        ),
        sa.PrimaryKeyConstraint("instrument_id", "constraint_id"),
        schema="across",
    )
    op.add_column(
        "instrument",
        sa.Column("visibility_type", sa.String(length=10), nullable=True),
        schema="across",
    )
    op.add_column(
        "observatory",
        sa.Column(
            "operational_begin_date",
            sa.DateTime(),
            nullable=True,
        ),
        schema="across",
    )
    op.add_column(
        "observatory",
        sa.Column("operational_end_date", sa.DateTime(), nullable=True),
        schema="across",
    )
    op.execute(
        "UPDATE across.observatory SET operational_begin_date = '1970-01-01 00:00:00'::timestamp"
    )
    op.alter_column(
        "observatory", "operational_begin_date", nullable=False, schema="across"
    )

    ### add default constraints to our pointed instruments
    # For all pointed intruments add the following constraints:
    #   Sun angle constraint of 45 degrees
    #   Moon angle constraint of 20 degrees
    #   Earth angle constraint of 20 degrees

    # For all-sky instruments add the following constraint:
    #   Earth angle constraint of 0 degrees

    bind = op.get_bind()
    session = orm.Session(bind=bind, expire_on_commit=False)

    sun45constraint = models.Constraint(
        id=uuid.UUID("d530a37d-0fc1-4ea3-8bae-1ab4940308b5"),
        constraint_type=ConstraintType.SUN,
        constraint_parameters=SunAngleConstraint(min_angle=45).model_dump(),
    )
    moon20constraint = models.Constraint(
        id=uuid.UUID("3390c3f9-62ea-4ee1-a94e-cc5178a7a383"),
        constraint_type=ConstraintType.MOON,
        constraint_parameters=MoonAngleConstraint(min_angle=20).model_dump(),
    )
    earth20constraint = models.Constraint(
        id=uuid.UUID("70d3f9cb-2550-4064-9808-36a75f9cae87"),
        constraint_type=ConstraintType.EARTH,
        constraint_parameters=EarthLimbConstraint(min_angle=20).model_dump(),
    )
    earth0constraint = models.Constraint(
        id=uuid.UUID("5a2bcefc-f08e-4d4f-a2a9-1dd526638884"),
        constraint_type=ConstraintType.EARTH,
        constraint_parameters=EarthLimbConstraint(min_angle=0).model_dump(),
    )
    pointed_instruments = (
        session.query(models.Instrument)
        .where(models.Instrument.field_of_view != InstrumentFOV.ALL_SKY.value)
        .all()
    )

    for pointed_instrument in pointed_instruments:
        pointed_instrument.constraints = [
            sun45constraint,
            moon20constraint,
            earth20constraint,
        ]
        pointed_instrument.visibility_type = VisibilityType.EPHEMERIS
        session.add(pointed_instrument)

    all_sky_instruments = (
        session.query(models.Instrument)
        .where(models.Instrument.field_of_view == InstrumentFOV.ALL_SKY.value)
        .all()
    )

    for all_sky_instrument in all_sky_instruments:
        all_sky_instrument.constraints = [earth0constraint]
        all_sky_instrument.visibility_type = VisibilityType.EPHEMERIS
        session.add(all_sky_instrument)

    session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("observatory", "operational_end_date", schema="across")
    op.drop_column("observatory", "operational_begin_date", schema="across")
    op.drop_column("instrument", "visibility_type", schema="across")
    op.drop_table("instrument_constraint", schema="across")
    op.drop_table("constraint", schema="across")
    # ### end Alembic commands ###
