"""add broker events and alerts

Revision ID: 89e86b4acb06
Revises: a99c9ee52dce
Create Date: 2026-04-14 14:56:15.412358

"""

from typing import Sequence, Union
from uuid import UUID

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geography
from sqlalchemy import orm

import migrations.versions.model_snapshots.models_2026_04_16 as models

# revision identifiers, used by Alembic.
revision: str = "89e86b4acb06"
down_revision: Union[str, None] = "a99c9ee52dce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

broker_alert_permission_values = {
    "name": "system:broker-alert:write",
    "id": UUID("a7ba23f0-fe2b-4956-a157-6e4ebf88eb7b"),
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "broker_event",
        sa.Column("event_datetime", sa.DateTime(), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="across",
    )
    op.create_table(
        "broker_alert",
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("checksum", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("broker_name", sa.String(length=50), nullable=False),
        sa.Column("data_source", sa.String(length=100), nullable=False),
        sa.Column("external_event_id", sa.String(length=100), nullable=False),
        sa.Column("broker_received_on", sa.DateTime(), nullable=False),
        sa.Column("broker_event_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["broker_event_id"],
            ["across.broker_event.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="across",
    )
    op.create_table(
        "localization",
        sa.Column("ra", sa.REAL(), nullable=True),
        sa.Column("dec", sa.REAL(), nullable=True),
        sa.Column("probability_enclosed", sa.REAL(), nullable=True),
        sa.Column("broker_alert_id", sa.UUID(), nullable=False),
        sa.Column("broker_event_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["broker_alert_id"],
            ["across.broker_alert.id"],
        ),
        sa.ForeignKeyConstraint(
            ["broker_event_id"],
            ["across.broker_event.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="across",
    )
    op.create_table(
        "localization_contour",
        sa.Column(
            "contour",
            Geography(
                geometry_type="POLYGON",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="across",
    )
    op.create_table(
        "localization_localization_contour",
        sa.Column("localization_id", sa.UUID(), nullable=False),
        sa.Column("localization_contour_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["localization_contour_id"],
            ["across.localization_contour.id"],
        ),
        sa.ForeignKeyConstraint(
            ["localization_id"],
            ["across.localization.id"],
        ),
        sa.PrimaryKeyConstraint("localization_id", "localization_contour_id"),
        schema="across",
    )
    # ### end Alembic commands ###
    bind = op.get_bind()
    session = orm.Session(bind=bind, expire_on_commit=False)

    # system role by uuid from db
    system_role: models.Role = session.get(
        models.Role, UUID("ed6a2440-79c8-454a-8284-f826a27f6e04"), with_for_update=True
    )  # type: ignore
    # add permission
    system_role.permissions.append(models.Permission(**broker_alert_permission_values))

    session.commit()


def downgrade() -> None:
    bind = op.get_bind()
    session = orm.Session(bind=bind, expire_on_commit=False)

    tle_permission: models.Permission = session.get(
        models.Permission, broker_alert_permission_values["id"]
    )  # type: ignore
    session.delete(tle_permission)

    session.commit()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("localization_localization_contour", schema="across")
    op.drop_index(
        "idx_localization_contour_contour",
        table_name="localization_contour",
        schema="across",
        postgresql_using="gist",
    )
    op.drop_table("localization_contour", schema="across")
    op.drop_table("localization", schema="across")
    op.drop_table("broker_alert", schema="across")
    op.drop_table("broker_event", schema="across")
    # ### end Alembic commands ###
