"""adding observation request models

Revision ID: 6a81b90801ad
Revises: 15fb704e6b6a
Create Date: 2026-05-26 13:47:37.611210

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geography
from sqlalchemy import orm, select

import migrations.versions.model_snapshots.models_2026_05_26 as models

# revision identifiers, used by Alembic.
revision: str = "6a81b90801ad"
down_revision: Union[str, None] = "15fb704e6b6a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "proposal",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="across",
    )
    op.create_table(
        "observation_request",
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("status_reason", sa.String(), nullable=True),
        sa.Column("science_justification", sa.String(), nullable=False),
        sa.Column("object_ra", sa.Float(), nullable=False),
        sa.Column("object_dec", sa.Float(), nullable=False),
        sa.Column("object_position_error", sa.Float(), nullable=True),
        sa.Column("object_apparent_magnitude", sa.Float(), nullable=False),
        sa.Column(
            "object_position",
            Geography(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("object_name", sa.String(length=100), nullable=False),
        sa.Column("date_range_begin", sa.DateTime(), nullable=False),
        sa.Column("date_range_end", sa.DateTime(), nullable=False),
        sa.Column("exposure_time", sa.Float(), nullable=True),
        sa.Column("proposal_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("anonymized", sa.Boolean(), nullable=False),
        sa.Column("instrument_id", sa.UUID(), nullable=True),
        sa.Column("instrument_configuration", sa.JSON(), nullable=True),
        sa.Column("is_too", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=True),
        sa.Column("created_on", sa.DateTime(), nullable=False),
        sa.Column("modified_by_id", sa.UUID(), nullable=True),
        sa.Column("modified_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["across.instrument.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["across.observation_request.id"],
        ),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["across.proposal.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="across",
    )
    op.create_index(
        "ix_observation_request_created_by_id",
        "observation_request",
        ["created_by_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        "ix_observation_request_date_range",
        "observation_request",
        ["date_range_begin", "date_range_end"],
        unique=False,
        schema="across",
    )
    op.create_index(
        "ix_observation_request_date_range_begin",
        "observation_request",
        ["date_range_begin"],
        unique=False,
        schema="across",
    )
    op.create_index(
        "ix_observation_request_date_range_end",
        "observation_request",
        ["date_range_end"],
        unique=False,
        schema="across",
    )
    op.create_index(
        "ix_observation_request_instrument_id",
        "observation_request",
        ["instrument_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        "ix_observation_request_object_position",
        "observation_request",
        ["object_position"],
        unique=False,
        schema="across",
        postgresql_using="gist",
    )
    op.create_index(
        "ix_observation_request_parent_id",
        "observation_request",
        ["parent_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        "ix_observation_request_proposal_id",
        "observation_request",
        ["proposal_id"],
        unique=False,
        schema="across",
    )
    op.create_index(
        "ix_observation_request_status",
        "observation_request",
        ["status"],
        unique=False,
        schema="across",
    )
    op.add_column(
        "instrument",
        sa.Column("can_accept_toos", sa.Boolean(), nullable=True),
        schema="across",
    )
    op.add_column(
        "telescope",
        sa.Column("can_accept_toos", sa.Boolean(), nullable=True),
        schema="across",
    )
    # ### end Alembic commands ###

    # Step 2: populate column with values
    bind = op.get_bind()
    session = orm.Session(bind=bind, expire_on_commit=False)

    telescopes = session.scalars(select(models.Telescope).with_for_update())
    for telescope in list(telescopes.all()):
        telescope.can_accept_toos = False

    instruments = session.scalars(select(models.Instrument).with_for_update())
    for instrument in list(instruments.all()):
        instrument.can_accept_toos = False
    session.commit()

    # Step 3: set column to not nullable.
    op.alter_column(
        table_name="telescope",
        column_name="can_accept_toos",
        nullable=False,
        schema="across",
    )
    op.alter_column(
        table_name="instrument",
        column_name="can_accept_toos",
        nullable=False,
        schema="across",
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("telescope", "can_accept_toos", schema="across")
    op.drop_column("instrument", "can_accept_toos", schema="across")
    op.drop_index(
        "ix_observation_request_status",
        table_name="observation_request",
        schema="across",
    )
    op.drop_index(
        "ix_observation_request_proposal_id",
        table_name="observation_request",
        schema="across",
    )
    op.drop_index(
        "ix_observation_request_parent_id",
        table_name="observation_request",
        schema="across",
    )
    op.drop_index(
        "ix_observation_request_object_position",
        table_name="observation_request",
        schema="across",
        postgresql_using="gist",
    )
    op.drop_index(
        "ix_observation_request_instrument_id",
        table_name="observation_request",
        schema="across",
    )
    op.drop_index(
        "ix_observation_request_date_range_end",
        table_name="observation_request",
        schema="across",
    )
    op.drop_index(
        "ix_observation_request_date_range_begin",
        table_name="observation_request",
        schema="across",
    )
    op.drop_index(
        "ix_observation_request_date_range",
        table_name="observation_request",
        schema="across",
    )
    op.drop_index(
        "ix_observation_request_created_by_id",
        table_name="observation_request",
        schema="across",
    )
    op.drop_index(
        "idx_observation_request_object_position",
        table_name="observation_request",
        schema="across",
        postgresql_using="gist",
    )
    op.drop_table("observation_request", schema="across")
    op.drop_table("proposal", schema="across")
    # ### end Alembic commands ###
