"""add observation footprint observation id idx

Revision ID: 842f5166cdfb
Revises: 9e16519fbb23
Create Date: 2026-10-07 12:49:39.573205

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "842f5166cdfb"
down_revision: Union[str, None] = "9e16519fbb23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_observation_footprint_observation_id",
        "observation_footprint",
        ["observation_id"],
        unique=False,
        schema="across",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_observation_footprint_observation_id",
        table_name="observation_footprint",
        schema="across",
    )
    # ### end Alembic commands ###
