"""add observation_count column to Schedule table

Revision ID: 2a3f02d11576
Revises: d56250541a9b
Create Date: 2025-11-17 12:57:23.895703

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy import orm, select

import migrations.versions.model_snapshots.models_2025_11_17 as models

# revision identifiers, used by Alembic.
revision: str = "2a3f02d11576"
down_revision: Union[str, None] = "d56250541a9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedule",
        sa.Column("observation_count", sa.Integer(), nullable=True),
        schema="across",
    )

    bind = op.get_bind()
    session = orm.Session(bind=bind, expire_on_commit=False)

    schedules = session.scalars(select(models.Schedule).with_for_update())

    for schedule in list(schedules.all()):
        schedule.observation_count = len(schedule.observations)

    session.commit()

    op.alter_column("schedule", "observation_count", nullable=False, schema="across")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("schedule", "observation_count", schema="across")
    # ### end Alembic commands ###
