"""adding daterange index to schedule

Revision ID: 7264308ca648
Revises: 7f001eadcb4a
Create Date: 2025-05-21 14:39:01.709574

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7264308ca648"
down_revision: Union[str, None] = "7f001eadcb4a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_schedule_date_range",
        "schedule",
        ["date_range_begin", "date_range_end"],
        unique=False,
        schema="across",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_schedule_date_range", table_name="schedule", schema="across")
    # ### end Alembic commands ###
