"""changing bandpass definitions for observations

Revision ID: e4ec21aebc19
Revises: ed3a08dbfcc0
Create Date: 2025-04-21 14:15:30.165398

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e4ec21aebc19"
down_revision: Union[str, None] = "ed3a08dbfcc0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "observation",
        sa.Column("max_wavelength", sa.Float(), nullable=True),
        schema="across",
    )
    op.add_column(
        "observation",
        sa.Column("min_wavelength", sa.Float(), nullable=True),
        schema="across",
    )
    op.add_column(
        "observation",
        sa.Column("peak_wavelength", sa.Float(), nullable=True),
        schema="across",
    )
    op.drop_column("observation", "bandwidth", schema="across")
    op.drop_column("observation", "central_wavelength", schema="across")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "observation",
        sa.Column("central_wavelength", sa.Float(precision=2), nullable=True),
        schema="across",
    )
    op.add_column(
        "observation",
        sa.Column("bandwidth", sa.Float(precision=2), nullable=True),
        schema="across",
    )
    op.drop_column("observation", "peak_wavelength", schema="across")
    op.drop_column("observation", "min_wavelength", schema="across")
    op.drop_column("observation", "max_wavelength", schema="across")
    # ### end Alembic commands ###
