"""add observation schedule id idx

Revision ID: f24460b144c4
Revises: 6a81b90801ad
Create Date: 2026-06-10 13:19:22.539991

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f24460b144c4"
down_revision: Union[str, None] = "6a81b90801ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_across_observation_schedule_id"),
        "observation",
        ["schedule_id"],
        unique=False,
        schema="across",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_across_observation_schedule_id"),
        table_name="observation",
        schema="across",
    )
    # ### end Alembic commands ###
