"""add fermi

Revision ID: 7f001eadcb4a
Revises: 043885e1cd78
Create Date: 2025-05-14 15:15:20.099908

"""

import uuid
from typing import Sequence, Union

import numpy as np
from across.tools import EnergyBandpass, convert_to_wave
from across.tools.core import enums as tools_enums
from alembic import op
from sqlalchemy import orm, select

from across_server.core.enums.ephemeris_type import EphemerisType
from across_server.core.enums.instrument_fov import InstrumentFOV
from across_server.core.enums.instrument_type import InstrumentType
from migrations.db_util import ACROSSFootprintPoint, create_geography
from migrations.versions.model_snapshots.models_2025_05_15 import (
    Filter,
    Footprint,
    Group,
    GroupRole,
    Instrument,
    Observatory,
    ObservatoryEphemerisType,
    Permission,
    Telescope,
    TLEParameters,
)

# revision identifiers, used by Alembic.
revision: str = "7f001eadcb4a"
down_revision: Union[str, None] = "043885e1cd78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# LAT has a FOV of 2.4 steradians
radius = 50  # degrees
thetas = np.linspace(0, -2 * np.pi, 200)
ras = radius * np.cos(thetas)
decs = radius * np.sin(thetas)
LAT_FOOTPRINT = [[{"x": ras[i], "y": decs[i]} for i in range(len((ras)))]]

# Info about LAT and GBM bandpasses found here:
# https://heasarc.gsfc.nasa.gov/docs/heasarc/missions/fermi.html
LAT_ENERGY_BANDPASS = EnergyBandpass(
    min=0.02,
    max=300,
    unit=tools_enums.EnergyUnit.GeV,
)
LAT_WAVELENGTH_BANDPASS = convert_to_wave(LAT_ENERGY_BANDPASS)

GBM_ENERGY_BANDPASS = EnergyBandpass(
    min=0.008,
    max=40,
    unit=tools_enums.EnergyUnit.MeV,
)
GBM_WAVELENGTH_BANDPASS = convert_to_wave(GBM_ENERGY_BANDPASS)

OBSERVATORY = {
    "name": "Fermi Gamma-ray Space Telescope",
    "short_name": "Fermi",
    "observatory_type": "SPACE_BASED",
    "reference_url": "https://fermi.gsfc.nasa.gov",
    "is_operational": True,
    "telescopes": [
        {
            "name": "Large Area Telescope",
            "short_name": "LAT",
            "id": "86f6849d-f634-4769-9aff-88907c6d455c",
            "is_operational": True,
            "reference_url": "https://fermi.gsfc.nasa.gov",
            "instruments": [
                {
                    "name": "Large Area Telescope",
                    "short_name": "LAT",
                    "id": "43d8dab5-0b79-45b5-8719-f301b1bd573d",
                    "field_of_view": InstrumentFOV.POLYGON.value,
                    "footprint": LAT_FOOTPRINT,
                    "is_operational": True,
                    "reference_url": "https://heasarc.gsfc.nasa.gov/docs/heasarc/missions/fermi.html",
                    "type": InstrumentType.CALORIMETER.value,
                    "filters": [
                        {
                            "name": "Fermi LAT Bandpass",
                            "min_wavelength": LAT_WAVELENGTH_BANDPASS.min,
                            "max_wavelength": LAT_WAVELENGTH_BANDPASS.max,
                            "is_operational": True,
                            "reference_url": "https://heasarc.gsfc.nasa.gov/docs/heasarc/missions/fermi.html",
                        }
                    ],
                },
            ],
        },
        {
            "name": "Gamma-ray Burst Monitor",
            "short_name": "GBM",
            "id": "327836f4-c0bf-45a1-be4c-9e94bf9f495d",
            "is_operational": True,
            "reference_url": "https://fermi.gsfc.nasa.gov",
            "instruments": [
                {
                    "name": "Gamma-ray Burst Monitor",
                    "short_name": "GBM",
                    "id": "3e56b7e0-a020-4c8d-8d85-07435b2b36c1",
                    "field_of_view": InstrumentFOV.ALL_SKY.value,
                    "footprint": [],
                    "is_operational": True,
                    "reference_url": "https://heasarc.gsfc.nasa.gov/docs/heasarc/missions/fermi.html",
                    "type": InstrumentType.SCINTILLATOR.value,
                    "filters": [
                        {
                            "name": "Fermi GBM Bandpass",
                            "min_wavelength": GBM_WAVELENGTH_BANDPASS.min,
                            "max_wavelength": GBM_WAVELENGTH_BANDPASS.max,
                            "is_operational": True,
                            "reference_url": "https://heasarc.gsfc.nasa.gov/docs/heasarc/missions/fermi.html",
                        }
                    ],
                }
            ],
        },
    ],
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = orm.Session(bind=bind, expire_on_commit=False)

    # create group based off the observatory
    group = Group(
        id=uuid.UUID("2d1919c9-728b-4d8c-8afb-ad60c63eab4e"),
        name=OBSERVATORY["name"],
        short_name=OBSERVATORY["short_name"],
    )
    session.add(group)

    # create group admin
    permissions = (
        session.query(Permission)
        .filter(
            Permission.name.in_(
                [
                    "group:user:write",
                    "group:role:write",
                    "group:write",
                    "group:read",
                    "group:observatory:write",
                    "group:telescope:write",
                    "group:schedule:write",
                ]
            )
        )
        .all()
    )
    fermi_group_admin = GroupRole(
        id=uuid.UUID("449c19ee-7b09-4b4d-ae52-99885a37f7be"),
        name="Fermi Group Admin",
        permissions=permissions,
        group=group,
    )
    session.add(fermi_group_admin)

    # create observatory
    observatory_insert = Observatory(
        id=uuid.UUID("ac071adf-bdc1-4fd7-9bf6-3918d9f65498"),
        name=OBSERVATORY["name"],
        short_name=OBSERVATORY["short_name"],
        type=OBSERVATORY["observatory_type"],
        reference_url=OBSERVATORY["reference_url"],
        is_operational=OBSERVATORY["is_operational"],
        group=group,
    )
    session.add(observatory_insert)
    observatory_id = observatory_insert.id

    # get the telescopes
    telescopes = OBSERVATORY["telescopes"]
    for telescope in telescopes:  #  type:ignore
        # create the telescope record
        telescope_insert = Telescope(
            id=telescope["id"],
            name=telescope["name"],
            short_name=telescope["short_name"],
            reference_url=telescope["reference_url"],
            is_operational=telescope["is_operational"],
            observatory_id=observatory_id,
        )
        session.add(telescope_insert)
        telescope_id = telescope_insert.id

        # get the instruments
        instruments = telescope["instruments"]  #  type:ignore
        for instrument in instruments:
            # create the instrument record
            instrument_insert = Instrument(
                id=instrument["id"],
                name=instrument["name"],
                short_name=instrument["short_name"],
                type=instrument["type"],
                field_of_view=instrument["field_of_view"],
                reference_url=instrument["reference_url"],
                is_operational=instrument["is_operational"],
                telescope_id=telescope_id,
            )
            session.add(instrument_insert)
            instrument_id = instrument_insert.id

            footprints = instrument["footprint"]
            for footprint in footprints:
                # convert the input footprint to the string polygon
                vertices = []
                for point in footprint:
                    vertices.append(ACROSSFootprintPoint(x=point["x"], y=point["y"]))

                polygon = create_geography(polygon=vertices)

                # create the footprint model record
                footprint_insert = Footprint(
                    polygon=polygon, instrument_id=instrument_id
                )
                session.add(footprint_insert)

            filters = instrument["filters"]
            for filter in filters:
                filter_insert = Filter(**filter)
                filter_insert.instrument_id = instrument_id
                session.add(filter_insert)

    # Add TLEParameters for Fermi
    ephemeris_type = ObservatoryEphemerisType(
        observatory_id=observatory_id,
        ephemeris_type=EphemerisType.TLE,
        priority=1,
    )

    session.add(ephemeris_type)

    tle_parameters = TLEParameters(
        observatory_id=observatory_id,
        norad_id=33053,
        norad_satellite_name="FGRST (GLAST)",
    )
    session.add(tle_parameters)

    session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    group = session.scalar(select(Group).filter_by(name=OBSERVATORY["name"]))
    observatory = session.scalar(
        select(Observatory).filter_by(name=OBSERVATORY["name"])
    )
    observatory_id = observatory.id  # type: ignore
    tle_parameters = session.scalar(
        select(TLEParameters).filter_by(observatory_id=observatory_id)
    )

    session.delete(group)
    session.delete(observatory)
    session.delete(tle_parameters)

    session.commit()
    # ### end Alembic commands ###
