"""adding footprint to observation table

Revision ID: 90c0b855ecde
Revises: 59e4b9fd7386
Create Date: 2026-02-19 14:51:09.944155

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision: str = "90c0b855ecde"
down_revision: Union[str, None] = "59e4b9fd7386"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "observation_footprint",
        sa.Column("observation_id", sa.UUID(), nullable=False),
        sa.Column(
            "polygon",
            Geography(
                geometry_type="POLYGON",
                srid=4326,
                from_text="ST_GeogFromText",
                name="geography",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["across.observation.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="across",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_observation_footprint_polygon",
        table_name="observation_footprint",
        schema="across",
        postgresql_using="gist",
    )
    op.drop_table("observation_footprint", schema="across")
    # ### end Alembic commands ###
