"""adding daterange index to schedule

Revision ID: 7264308ca648
Revises: 2b00546497c1
Create Date: 2025-05-21 14:39:01.709574

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7264308ca648"
down_revision: Union[str, None] = "2b00546497c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_schedule_date_range",
        "schedule",
        ["date_range_begin", "date_range_end"],
        unique=False,
        schema="across",
    )
    op.create_index(
        "ix_schedule_date_range_begin",
        "schedule",
        ["date_range_begin"],
        unique=False,
        schema="across",
    )
    op.create_index(
        "ix_schedule_date_range_end",
        "schedule",
        ["date_range_end"],
        unique=False,
        schema="across",
    )
    op.create_index(
        "ix_schedule_checksum",
        "schedule",
        ["checksum"],
        unique=True,
        schema="across",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_schedule_date_range", table_name="schedule", schema="across")
    op.drop_index(
        "ix_schedule_date_range_begin", table_name="schedule", schema="across"
    )
    op.drop_index("ix_schedule_date_range_end", table_name="schedule", schema="across")
    op.drop_index("ix_schedule_checksum", table_name="schedule", schema="across")
    # ### end Alembic commands ###
