"""jwst ephemeris type to jpl

Revision ID: 9c6db8cdfe82
Revises: 59faf999b470
Create Date: 2025-10-06 14:58:49.007854

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy import orm

from across_server.core.enums import EphemerisType
from migrations.versions.model_snapshots import models_2025_09_02 as models

# revision identifiers, used by Alembic.
revision: str = "9c6db8cdfe82"
down_revision: Union[str, None] = "59faf999b470"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = orm.Session(bind=bind, expire_on_commit=False)

    # get jwst ephemeris type for tle, and set priority to 2
    jwst_tle_ephemeris_type = (
        session.query(models.ObservatoryEphemerisType)
        .where(
            models.ObservatoryEphemerisType.id == "cf5cfa4c-8406-4460-aa4e-5680843f6afd"
        )
        .first()
    )
    jwst_tle_ephemeris_type.priority = 2  # type: ignore

    jwst_jpl_ephemeris_parameters = models.JPLEphemerisParameters(
        id="9397daca-218a-4aff-b09e-3398e31dd795",
        observatory_id="fefe0ddc-07af-4312-b3a8-051c4e646619",
        naif_id=-170,
    )

    jwst_jpl_ephmeris_type = models.ObservatoryEphemerisType(
        id="702c94c8-f87a-4d74-9a6c-ab0b8bdf85f3",
        observatory_id="fefe0ddc-07af-4312-b3a8-051c4e646619",
        priority=1,
        ephemeris_type=EphemerisType.JPL.value,
        parameters=jwst_jpl_ephemeris_parameters,
    )

    session.add_all(
        [jwst_tle_ephemeris_type, jwst_jpl_ephemeris_parameters, jwst_jpl_ephmeris_type]
    )

    session.commit()

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = orm.Session(bind=bind, expire_on_commit=False)

    # get jwst ephemeris type for tle, and set priority back to 1
    jwst_tle_ephemeris_type = (
        session.query(models.ObservatoryEphemerisType)
        .where(
            models.ObservatoryEphemerisType.id == "cf5cfa4c-8406-4460-aa4e-5680843f6afd"
        )
        .first()
    )
    jwst_tle_ephemeris_type.priority = 1  # type: ignore

    session.add(jwst_tle_ephemeris_type)

    session.delete(
        session.query(models.JPLEphemerisParameters)
        .where(
            models.JPLEphemerisParameters.id == "9397daca-218a-4aff-b09e-3398e31dd795"
        )
        .first()
    )
    session.delete(
        session.query(models.ObservatoryEphemerisType)
        .where(
            models.ObservatoryEphemerisType.id == "702c94c8-f87a-4d74-9a6c-ab0b8bdf85f3"
        )
        .first()
    )

    session.commit()
    # ### end Alembic commands ###
