"""resolve ix naming

Revision ID: ce236d6cd364
Revises: 00b3a6244b1c
Create Date: 2026-02-24 16:07:18.255481

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ce236d6cd364"
down_revision: Union[str, None] = "00b3a6244b1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # renaming the index to the alembic auto generated name
    op.drop_index(op.f("ix_user_is_deleted"), table_name="user", schema="across")
    op.create_index(
        op.f("ix_across_user_is_deleted"),
        "user",
        ["is_deleted"],
        unique=False,
        schema="across",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_across_user_is_deleted"), table_name="user", schema="across")
    op.create_index(
        op.f("ix_user_is_deleted"),
        "user",
        ["is_deleted"],
        unique=False,
        schema="across",
    )
    # ### end Alembic commands ###
