"""adding fov and nulling



Revision ID: 80ed2c402962
Revises: 0f2036717762
Create Date: 2025-04-30 15:13:09.355575

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision: str = "80ed2c402962"
down_revision: Union[str, None] = "0f2036717762"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "instrument",
        sa.Column("field_of_view", sa.String(length=50), nullable=False),
        schema="across",
    )
    op.alter_column(
        "observation",
        "pointing_ra",
        existing_type=sa.REAL(),
        nullable=True,
        schema="across",
    )
    op.alter_column(
        "observation",
        "pointing_dec",
        existing_type=sa.REAL(),
        nullable=True,
        schema="across",
    )
    op.alter_column(
        "observation",
        "pointing_position",
        existing_type=Geography(
            geometry_type="POINT",
            srid=4326,
            from_text="ST_GeogFromText",
            name="geography",
            nullable=False,
        ),
        nullable=True,
        schema="across",
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "observation",
        "pointing_position",
        existing_type=Geography(
            geometry_type="POINT",
            srid=4326,
            from_text="ST_GeogFromText",
            name="geography",
            nullable=False,
        ),
        nullable=False,
        schema="across",
    )
    op.alter_column(
        "observation",
        "pointing_dec",
        existing_type=sa.REAL(),
        nullable=False,
        schema="across",
    )
    op.alter_column(
        "observation",
        "pointing_ra",
        existing_type=sa.REAL(),
        nullable=False,
        schema="across",
    )
    op.drop_column("instrument", "field_of_view", schema="across")
    # ### end Alembic commands ###
