"""create ixpe

Revision ID: a6590318e932
Revises: 043885e1cd78
Create Date: 2025-05-14 15:21:03.729061

"""

from __future__ import annotations

import uuid
from typing import Sequence, Union

from across.tools import EnergyBandpass, convert_to_wave
from across.tools import enums as tools_enums
from alembic import op
from sqlalchemy import orm

from across_server.core.enums import EphemerisType, InstrumentFOV, InstrumentType
from across_server.core.enums.observatory_type import ObservatoryType
from migrations.build_records import ssa_records
from migrations.db_util import arcmin_to_deg
from migrations.versions.model_snapshots import models_2025_05_15 as snapshot_models

# revision identifiers, used by Alembic.
revision: str = "a6590318e932"
down_revision: Union[str, None] = "043885e1cd78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# 12 arcmin x 12 arcmin square
footprint: list[list[dict]] = [
    [
        {"x": arcmin_to_deg(-6.0), "y": arcmin_to_deg(-6.0)},
        {"x": arcmin_to_deg(6.0), "y": arcmin_to_deg(-6.0)},
        {"x": arcmin_to_deg(6.0), "y": arcmin_to_deg(6.0)},
        {"x": arcmin_to_deg(-6.0), "y": arcmin_to_deg(6.0)},
        {"x": arcmin_to_deg(-6.0), "y": arcmin_to_deg(-6.0)},
    ]
]

IXPE_ENERGY_BANDPASS = EnergyBandpass(
    min=2.0,
    max=8.0,
    unit=tools_enums.EnergyUnit.keV,
)
IXPE_WAVELENGTH_BANDPASS = convert_to_wave(IXPE_ENERGY_BANDPASS)

OBSERVATORY = {
    "id": uuid.UUID("9864f892-a980-442c-a0c9-f35e26e598dd"),
    "name": "Imaging X-Ray Polarimetry Explorer",
    "short_name": "IXPE",
    "type": ObservatoryType.SPACE_BASED.value,
    "reference_url": "https://ixpe.msfc.nasa.gov/index.html",
    "is_operational": True,
    "telescopes": [
        {
            "id": uuid.UUID("be6eeadc-9b7c-481d-81bd-4d1314dc0d49"),
            "name": "Imaging X-Ray Polarimetry Explorer",
            "short_name": "IXPE",
            "is_operational": True,
            "reference_url": "https://ixpe.msfc.nasa.gov/index.html",
            "instruments": [
                {
                    "id": uuid.UUID("96d3dd34-a49e-4618-bef2-6eaca3aa26e6"),
                    "name": "Imaging X-Ray Polarimetry Explorer",
                    "short_name": "IXPE",
                    "reference_url": "https://heasarc.gsfc.nasa.gov/docs/heasarc/missions/ixpe.html",
                    "footprint": footprint,
                    "field_of_view": InstrumentFOV.POLYGON.value,
                    "is_operational": True,
                    "type": InstrumentType.POLARIMETER.value,
                    "filters": [
                        {
                            "id": uuid.UUID("e3deb75a-fb6e-49b8-81ba-14c6d4fc0844"),
                            "name": "IXPE Bandpass",
                            "min_wavelength": IXPE_WAVELENGTH_BANDPASS.min,
                            "max_wavelength": IXPE_WAVELENGTH_BANDPASS.max,
                            "is_operational": True,
                            "reference_url": "https://heasarc.gsfc.nasa.gov/docs/heasarc/missions/ixpe.html",
                        }
                    ],
                }
            ],
        }
    ],
    "ephemeris_types": [
        {
            "id": uuid.UUID("c15e0707-f084-4b1c-8d8c-30b7d1199a91"),
            "ephemeris_type": EphemerisType.TLE,
            "priority": 1,
            "parameters": {
                "id": uuid.UUID("8b4b8310-61da-4a81-9d55-3fd23ce54736"),
                "norad_id": 49954,
                "norad_satellite_name": "IXPE",
            },
        }
    ],
    "group": {
        "id": uuid.UUID("38d478eb-630f-4d42-abbc-4a0bdf20909a"),
        "name": "IXPE Space Telescope",
        "short_name": "IXPE",
        "group_admin": {
            "id": uuid.UUID("72146235-8987-49a7-8ad4-6038a1900e49"),
            "name": "IXPE Group Admin",
        },
    },
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = orm.Session(bind=bind, expire_on_commit=False)

    records = ssa_records.build(session, OBSERVATORY, snapshot_models)

    session.add_all(records)
    session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    ssa_records.delete(session, OBSERVATORY, snapshot_models)

    session.commit()
    # ### end Alembic commands ###
