"""add fermi

Revision ID: 7f001eadcb4a
Revises: 043885e1cd78
Create Date: 2025-05-14 15:15:20.099908

"""

import uuid
from typing import Sequence, Union

import numpy as np
from across.tools import EnergyBandpass, convert_to_wave
from across.tools.core import enums as tools_enums
from alembic import op
from sqlalchemy import orm, select

from across_server.core.enums.ephemeris_type import EphemerisType
from across_server.core.enums.instrument_fov import InstrumentFOV
from across_server.core.enums.instrument_type import InstrumentType
from migrations.db_util import ACROSSFootprintPoint, create_geography
from migrations.versions.model_snapshots.models_2025_05_15 import (
    EarthLocationParameters,
    Filter,
    Footprint,
    Group,
    GroupRole,
    Instrument,
    JPLEphemerisParameters,
    Observatory,
    ObservatoryEphemerisType,
    Permission,
    SpiceKernelParameters,
    Telescope,
    TLEParameters,
)

# revision identifiers, used by Alembic.
revision: str = "7f001eadcb4a"
down_revision: Union[str, None] = "043885e1cd78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# LAT has a FOV of 2.4 steradians
radius = 50  # degrees
thetas = np.linspace(0, -2 * np.pi, 200)
ras = radius * np.cos(thetas)
decs = radius * np.sin(thetas)
LAT_FOOTPRINT = [[{"x": ras[i], "y": decs[i]} for i in range(len((ras)))]]

# Info about LAT and GBM bandpasses found here:
# https://heasarc.gsfc.nasa.gov/docs/heasarc/missions/fermi.html
LAT_ENERGY_BANDPASS = EnergyBandpass(
    min=0.02,
    max=300,
    unit=tools_enums.EnergyUnit.GeV,
)
LAT_WAVELENGTH_BANDPASS = convert_to_wave(LAT_ENERGY_BANDPASS)

GBM_ENERGY_BANDPASS = EnergyBandpass(
    min=0.008,
    max=40,
    unit=tools_enums.EnergyUnit.MeV,
)
GBM_WAVELENGTH_BANDPASS = convert_to_wave(GBM_ENERGY_BANDPASS)

OBSERVATORY = {
    "name": "Fermi Gamma-ray Space Telescope",
    "short_name": "Fermi",
    "type": "SPACE_BASED",
    "reference_url": "https://fermi.gsfc.nasa.gov",
    "is_operational": True,
    "telescopes": [
        {
            "name": "Large Area Telescope",
            "short_name": "LAT",
            "is_operational": True,
            "reference_url": "https://fermi.gsfc.nasa.gov",
            "instruments": [
                {
                    "name": "Large Area Telescope",
                    "short_name": "LAT",
                    "field_of_view": InstrumentFOV.POLYGON.value,
                    "footprint": LAT_FOOTPRINT,
                    "is_operational": True,
                    "reference_url": "https://heasarc.gsfc.nasa.gov/docs/heasarc/missions/fermi.html",
                    "type": InstrumentType.CALORIMETER.value,
                    "filters": [
                        {
                            "name": "Fermi LAT Bandpass",
                            "min_wavelength": LAT_WAVELENGTH_BANDPASS.min,
                            "max_wavelength": LAT_WAVELENGTH_BANDPASS.max,
                            "is_operational": True,
                            "reference_url": "https://heasarc.gsfc.nasa.gov/docs/heasarc/missions/fermi.html",
                        }
                    ],
                },
            ],
        },
        {
            "name": "Gamma-ray Burst Monitor",
            "short_name": "GBM",
            "is_operational": True,
            "reference_url": "https://fermi.gsfc.nasa.gov",
            "instruments": [
                {
                    "name": "Gamma-ray Burst Monitor",
                    "short_name": "GBM",
                    "field_of_view": InstrumentFOV.ALL_SKY.value,
                    "footprint": [],
                    "is_operational": True,
                    "reference_url": "https://heasarc.gsfc.nasa.gov/docs/heasarc/missions/fermi.html",
                    "type": InstrumentType.SCINTILLATOR.value,
                    "filters": [
                        {
                            "name": "Fermi GBM Bandpass",
                            "min_wavelength": GBM_WAVELENGTH_BANDPASS.min,
                            "max_wavelength": GBM_WAVELENGTH_BANDPASS.max,
                            "is_operational": True,
                            "reference_url": "https://heasarc.gsfc.nasa.gov/docs/heasarc/missions/fermi.html",
                        }
                    ],
                }
            ],
        },
    ],
    "ephemeris_types": [
        {
            "ephemeris_type": EphemerisType.TLE,
            "priority": 1,
            "parameters": {
                "norad_id": 33053,
                "norad_satellite_name": "FGRST (GLAST)",
            },
        }
    ],
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = orm.Session(bind=bind, expire_on_commit=False)

    # create group based off the observatory
    group = Group(
        id=uuid.UUID("2d1919c9-728b-4d8c-8afb-ad60c63eab4e"),
        name=OBSERVATORY["name"],
        short_name=OBSERVATORY["short_name"],
    )
    session.add(group)

    # create group admin
    permissions = (
        session.query(Permission).filter(Permission.name.contains("group")).all()
    )
    fermi_group_admin = GroupRole(
        id=uuid.UUID("449c19ee-7b09-4b4d-ae52-99885a37f7be"),
        name="Fermi Group Admin",
        permissions=permissions,
        group=group,
    )
    session.add(fermi_group_admin)

    telescopes = OBSERVATORY.pop("telescopes")
    ephemeris_types = OBSERVATORY.pop("ephemeris_types")

    # create observatory
    observatory_insert = Observatory(id=uuid.uuid4(), group=group, **OBSERVATORY)
    session.add(observatory_insert)
    observatory_id = observatory_insert.id

    # get the telescopes
    for telescope in telescopes:  #  type:ignore
        instruments = telescope.pop("instruments")
        # create the telescope record
        telescope_insert = Telescope(
            id=uuid.uuid4(), observatory_id=observatory_id, **telescope
        )
        session.add(telescope_insert)
        telescope_id = telescope_insert.id

        # get the instruments
        for instrument in instruments:
            footprints = instrument.pop("footprint")
            filters = instrument.pop("filters")

            # create the instrument record
            instrument_insert = Instrument(
                id=uuid.uuid4(), telescope_id=telescope_id, **instrument
            )
            session.add(instrument_insert)
            instrument_id = instrument_insert.id

            for footprint in footprints:
                # convert the input footprint to the string polygon
                vertices = []
                for point in footprint:
                    vertices.append(ACROSSFootprintPoint(x=point["x"], y=point["y"]))

                polygon = create_geography(polygon=vertices)

                # create the footprint model record
                footprint_insert = Footprint(
                    polygon=polygon, instrument_id=instrument_id
                )
                session.add(footprint_insert)

            for filter in filters:
                filter_insert = Filter(instrument_id=instrument_id, **filter)
                session.add(filter_insert)

    # Add Ephemeris Parameters for Fermi
    for ephemeris_type in ephemeris_types:  # type:ignore
        # create the ephemeris type record
        parameters = ephemeris_type.pop("parameters")
        ephemeris_type_insert = ObservatoryEphemerisType(
            id=uuid.uuid4(),
            observatory_id=observatory_id,
            **ephemeris_type,
        )
        session.add(ephemeris_type_insert)

        if ephemeris_type_insert.ephemeris_type == EphemerisType.TLE:
            tle_parameters = TLEParameters(
                id=uuid.uuid4(), observatory_id=observatory_id, **parameters
            )
            session.add(tle_parameters)

        if ephemeris_type_insert.ephemeris_type == EphemerisType.JPL:
            jpl_parameters = JPLEphemerisParameters(
                id=uuid.uuid4(), observatory_id=observatory_id, **parameters
            )
            session.add(jpl_parameters)

        if ephemeris_type_insert.ephemeris_type == EphemerisType.SPICE:
            spice_parameters = SpiceKernelParameters(
                id=uuid.uuid4(), observatory_id=observatory_id, **parameters
            )
            session.add(spice_parameters)

        if ephemeris_type_insert.ephemeris_type == EphemerisType.GROUND:
            ground_parameters = EarthLocationParameters(
                id=uuid.uuid4(), observatory_id=observatory_id, **parameters
            )
            session.add(ground_parameters)

    session.commit()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = orm.Session(bind=bind)

    group = session.scalar(select(Group).filter_by(name=OBSERVATORY["name"]))
    observatory = session.scalar(
        select(Observatory).filter_by(name=OBSERVATORY["name"])
    )
    session.delete(group)
    session.delete(observatory)

    tle_parameters = session.scalar(
        select(TLEParameters).filter_by(observatory_id=observatory.id)  # type:ignore
    )
    if tle_parameters:
        session.delete(tle_parameters)

    jpl_parameters = session.scalar(
        select(JPLEphemerisParameters).filter_by(
            observatory_id=observatory.id  # type:ignore
        )
    )
    if jpl_parameters:
        session.delete(jpl_parameters)

    spice_parameters = session.scalar(
        select(SpiceKernelParameters).filter_by(
            observatory_id=observatory.id  # type:ignore
        )
    )
    if spice_parameters:
        session.delete(spice_parameters)

    ground_parameters = session.scalar(
        select(EarthLocationParameters).filter_by(
            observatory_id=observatory.id  # type:ignore
        )
    )
    if ground_parameters:
        session.delete(ground_parameters)

    session.commit()
    # ### end Alembic commands ###
