"""frontend service account

Revision ID: a99c9ee52dce
Revises: 1613a21d5d5f
Create Date: 2026-02-24 16:25:31.471967

"""

from typing import Sequence, Union
from uuid import UUID, uuid4

from alembic import op
from sqlalchemy import orm, select

from across_server.core import config
from across_server.util.ssm import SSM
from migrations.build_records import service_account
from migrations.util.build_role import RoleData, build_role
from migrations.versions.model_snapshots import models_2025_08_08 as snapshot_models

# revision identifiers, used by Alembic.
revision: str = "a99c9ee52dce"
down_revision: Union[str, None] = "1613a21d5d5f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


SERVICE_ACCOUNT_DATA = service_account.ServiceAccountData(
    id=UUID("a13bbcdd-798d-43cd-bb2a-6b10347db2a3"),
    name="Frontend Service Account",
    description="The service account that is used by the frontend service in order to authenticate and authorize requests to the across server.",
    expiration_duration=36525,  # 100 years Rick and Morty!
)

permissions_data: dict[str, UUID] = {
    "system:login:write": UUID("897c2da8-34c0-4525-b6bb-e474ba549d95"),
    "system:user:write": UUID("c8316dcb-ad4f-401c-80ea-67b439bfb52c"),
}

roles_data: dict[str, RoleData] = {
    "frontend_system_role": {
        "id": UUID("2bfccc1f-6211-407d-8bb5-52557cffe5f7"),
        "name": "System Frontend Role",
        "permissions": ["system:login:write", "system:user:write"],
    },
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = orm.Session(bind=bind, expire_on_commit=False)

    if not config.is_local():
        # for non-local the generated ID will be stored in param store for added security
        SERVICE_ACCOUNT_DATA.id = uuid4()
        # use the default expiration duration (as of writing this, 30 days)
        SERVICE_ACCOUNT_DATA.expiration_duration = None

    record, secret = service_account.build(
        SERVICE_ACCOUNT_DATA, snapshot_models.ServiceAccount
    )

    if not config.is_local():
        SSM.put_parameter(
            str(SERVICE_ACCOUNT_DATA.id),
            config.FRONTEND_SERVICE_ACCOUNT_ID_PATH,
            config.APP_ENV,
            overwrite=True,
        )
        SSM.put_parameter(
            secret.key,
            config.FRONTEND_SERVICE_ACCOUNT_SECRET_PATH,
            config.APP_ENV,
            type="SecureString",
            overwrite=True,
        )

    record.roles = [
        build_role(
            role=role,
            role_cls=snapshot_models.Role,
            perms=permissions_data,
            permission_cls=snapshot_models.Permission,
        )
        for role in roles_data.values()
    ]

    session.add(record)
    session.commit()

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    session = orm.Session(bind=bind, expire_on_commit=False)

    id = SERVICE_ACCOUNT_DATA.id

    if not config.is_local():
        # pull the created ID from the param store
        id = UUID(
            SSM.get_parameter(config.FRONTEND_SERVICE_ACCOUNT_ID_PATH, config.APP_ENV)
        )

    account = session.scalar(select(snapshot_models.ServiceAccount).filter_by(id=id))
    session.delete(account)

    role = session.scalar(
        select(snapshot_models.Role).filter_by(
            id=roles_data["frontend_system_role"]["id"]
        )
    )
    session.delete(role)

    permissions = session.scalars(
        select(snapshot_models.Permission).filter(
            snapshot_models.Permission.id.in_(permissions_data.values())
        )
    )
    for permission in permissions:
        session.delete(permission)

    session.commit()
    # ### end Alembic commands ###
