filters: dict[str, list[dict[str, str | float | bool]]] = {
    "JWST_MIRI": [
        {
            "id": "6e08194b-464d-4db0-a56b-e49dafbede0d",
            "name": "F1140C",
            "min_wavelength": 110192.31,
            "max_wavelength": 115984.32,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-mid-infrared-instrument/miri-instrumentation/miri-filters-and-dispersers",
        },
        {
            "id": "26879316-3f81-4872-bf6d-87e824cb530d",
            "name": "F770W",
            "min_wavelength": 65850.0,
            "max_wavelength": 86850.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-mid-infrared-instrument/miri-instrumentation/miri-filters-and-dispersers",
        },
        {
            "id": "6e02f2d2-2378-4e84-bed2-2851cb3d1b1c",
            "name": "F1550C",
            "min_wavelength": 151484.42,
            "max_wavelength": 158774.72,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-mid-infrared-instrument/miri-instrumentation/miri-filters-and-dispersers",
        },
        {
            "id": "7c2a7b1d-2a1c-4eea-ac83-0900bad072f3",
            "name": "F1065C",
            "min_wavelength": 102814.37,
            "max_wavelength": 108406.44,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-mid-infrared-instrument/miri-instrumentation/miri-filters-and-dispersers",
        },
        {
            "id": "1d3f4320-daaf-40d1-84d4-308a7e2ea522",
            "name": "F2300C",
            "min_wavelength": 205088.99,
            "max_wavelength": 248674.92,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-mid-infrared-instrument/miri-instrumentation/miri-filters-and-dispersers",
        },
        {
            "id": "139204df-ae7f-45cd-8192-39370bb4d7ad",
            "name": "F1280W",
            "min_wavelength": 115910.0,
            "max_wavelength": 141200.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-mid-infrared-instrument/miri-instrumentation/miri-filters-and-dispersers",
        },
        {
            "id": "c88b0af6-bbae-4b71-a050-86aa5bf007a5",
            "name": "F1500W",
            "min_wavelength": 135280.0,
            "max_wavelength": 166370.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-mid-infrared-instrument/miri-instrumentation/miri-filters-and-dispersers",
        },
        {
            "id": "18cfec88-833e-456c-a438-67a8fccc1a4a",
            "name": "F2100W",
            "min_wavelength": 184810.0,
            "max_wavelength": 231560.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-mid-infrared-instrument/miri-instrumentation/miri-filters-and-dispersers",
        },
        {
            "id": "60698db0-a1cb-4c9b-9de2-468513adda80",
            "name": "F2550W",
            "min_wavelength": 233070.0,
            "max_wavelength": 267290.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-mid-infrared-instrument/miri-instrumentation/miri-filters-and-dispersers",
        },
        {
            "id": "8fb732a1-e0d7-429a-979d-b4954a374954",
            "name": "F1130W",
            "min_wavelength": 109590.0,
            "max_wavelength": 116660.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-mid-infrared-instrument/miri-instrumentation/miri-filters-and-dispersers",
        },
        {
            "id": "1f6ab068-3bcf-4d34-8264-173328039db5",
            "name": "F560W",
            "min_wavelength": 50540.0,
            "max_wavelength": 61680.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-mid-infrared-instrument/miri-instrumentation/miri-filters-and-dispersers",
        },
        {
            "id": "2cfa4fb0-0231-40ac-800e-b56002793775",
            "name": "F1000W",
            "min_wavelength": 90210.0,
            "max_wavelength": 108890.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-mid-infrared-instrument/miri-instrumentation/miri-filters-and-dispersers",
        },
        {
            "id": "19afdc6b-aaa7-4a77-b381-7fae779eb2d8",
            "name": "F1800W",
            "min_wavelength": 165210.0,
            "max_wavelength": 194960.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-mid-infrared-instrument/miri-instrumentation/miri-filters-and-dispersers",
        },
    ],
    "JWST_NIRCAM": [
        {
            "id": "dc4125a1-ada9-4817-ac5e-1ceed23d3eb5",
            "name": "F405N",
            "min_wavelength": 40293.7,
            "max_wavelength": 40739.6,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters",
        },
        {
            "id": "bf32f3f9-cbfb-49d7-a97a-349162cd9698",
            "name": "F277W",
            "min_wavelength": 24163.4,
            "max_wavelength": 31261.1,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters",
        },
        {
            "id": "f39d34e3-9705-4197-8e0e-71eb073faf80",
            "name": "F200W",
            "min_wavelength": 17554.0,
            "max_wavelength": 22254.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters",
        },
        {
            "id": "db9da5e4-2add-4268-b118-26c12a073bc8",
            "name": "F115W",
            "min_wavelength": 10142.0,
            "max_wavelength": 12812.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters",
        },
        {
            "id": "b1201e6a-4d2c-495f-9bf0-807b354297c5",
            "name": "F182M",
            "min_wavelength": 17225.0,
            "max_wavelength": 19675.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters",
        },
        {
            "id": "fadf6810-b597-4ddb-b55c-1ec37911e167",
            "name": "F360M",
            "min_wavelength": 34267.2,
            "max_wavelength": 38131.8,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters",
        },
        {
            "id": "61402d22-ad34-4c70-a7da-c0af570fd523",
            "name": "F070W",
            "min_wavelength": 6221.5,
            "max_wavelength": 7811.5,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters",
        },
        {
            "id": "4abed497-7397-44c9-9c35-920ad15ed128",
            "name": "F212N",
            "min_wavelength": 21103.0,
            "max_wavelength": 21333.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters",
        },
        {
            "id": "8b552330-ac28-498a-a71c-951ad4ef350d",
            "name": "F150W2",
            "min_wavelength": 10090.0,
            "max_wavelength": 23330.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters",
        },
        {
            "id": "b47d7b41-91b9-4c9a-a34e-ae18e8bb8a12",
            "name": "F480M",
            "min_wavelength": 46631.0,
            "max_wavelength": 49765.9,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters",
        },
        {
            "id": "a8379646-e1d0-492e-8d58-861d2c862ac2",
            "name": "F300M",
            "min_wavelength": 28294.8,
            "max_wavelength": 31551.3,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters",
        },
        {
            "id": "39fce95b-cd3d-48e9-9835-e4dcb1091fff",
            "name": "F140M",
            "min_wavelength": 13313.5,
            "max_wavelength": 14783.5,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters",
        },
        {
            "id": "1f3d2344-756d-4c6c-8383-62d9b6397750",
            "name": "F250M",
            "min_wavelength": 24127.4,
            "max_wavelength": 25940.9,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters",
        },
        {
            "id": "3e9d1e70-852e-4c2e-818b-3cacb9c3148b",
            "name": "F323N",
            "min_wavelength": 32172.8,
            "max_wavelength": 32551.2,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters",
        },
        {
            "id": "49b3be9f-0981-4944-b1be-fefe2b6ca380",
            "name": "F460M",
            "min_wavelength": 45158.2,
            "max_wavelength": 47468.8,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters",
        },
        {
            "id": "5f66296f-0a39-4a59-95c1-c51725cc5706",
            "name": "F335M",
            "min_wavelength": 31781.0,
            "max_wavelength": 35375.2,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters",
        },
        {
            "id": "0a2d906b-652b-410b-8da8-9879d8ce6217",
            "name": "F162M",
            "min_wavelength": 15424.0,
            "max_wavelength": 17124.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters",
        },
        {
            "id": "d63171a2-59d7-4fcc-bab2-7e792b547ef2",
            "name": "F090W",
            "min_wavelength": 7955.5,
            "max_wavelength": 10045.5,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters",
        },
        {
            "id": "4eb2fff4-f8d0-4175-a494-297d6b07e9ae",
            "name": "F356W",
            "min_wavelength": 31402.6,
            "max_wavelength": 39793.8,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters",
        },
        {
            "id": "24165cb1-9d46-48c7-a00a-ae4bb6a34edb",
            "name": "F210M",
            "min_wavelength": 19926.0,
            "max_wavelength": 22006.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters",
        },
        {
            "id": "bb019987-0a49-45b8-baa1-a681600dc7bc",
            "name": "F466N",
            "min_wavelength": 46293.2,
            "max_wavelength": 46806.7,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters",
        },
        {
            "id": "b3d53026-bfb4-461a-a3c5-4d6823f3286c",
            "name": "F150W",
            "min_wavelength": 13317.9,
            "max_wavelength": 16677.9,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters",
        },
        {
            "id": "607bc352-fe5a-4414-98f8-99e33f8a747d",
            "name": "F322W2",
            "min_wavelength": 24314.4,
            "max_wavelength": 40118.1,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters",
        },
        {
            "id": "59d98f4b-b8f2-4fe2-8a55-a6ffa86bc167",
            "name": "F470N",
            "min_wavelength": 46847.2,
            "max_wavelength": 47320.1,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters",
        },
        {
            "id": "3904c51a-be8c-41bc-b28f-680a2eac84dd",
            "name": "F410M",
            "min_wavelength": 38645.2,
            "max_wavelength": 43009.7,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters",
        },
        {
            "id": "31503d35-a80d-4382-8062-ff9339a46833",
            "name": "F164N",
            "min_wavelength": 16364.0,
            "max_wavelength": 16524.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters",
        },
        {
            "id": "8dd67840-0232-49ed-b246-4c66316ccde7",
            "name": "F444W",
            "min_wavelength": 38807.4,
            "max_wavelength": 49846.9,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters",
        },
        {
            "id": "1f7a9ddc-91b2-48dc-a96d-b682405a34af",
            "name": "F187N",
            "min_wavelength": 18642.0,
            "max_wavelength": 18842.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters",
        },
        {
            "id": "85696a0e-fab2-460a-a0a5-c33d2f1fdc10",
            "name": "F430M",
            "min_wavelength": 41672.0,
            "max_wavelength": 43982.6,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-camera/nircam-instrumentation/nircam-filters",
        },
    ],
    "JWST_NIRISS": [
        {
            "id": "3c28c892-dacc-4b56-8eee-633e9f3a01a7",
            "name": "F444W",
            "min_wavelength": 38800.0,
            "max_wavelength": 50230.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-imager-and-slitless-spectrograph/niriss-instrumentation/niriss-filters",
        },
        {
            "id": "44d47edf-66ae-4624-9ca9-36c4d107ee70",
            "name": "F430M",
            "min_wavelength": 41820.0,
            "max_wavelength": 43950.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-imager-and-slitless-spectrograph/niriss-instrumentation/niriss-filters",
        },
        {
            "id": "073c5e4a-ca86-460d-9de7-807c1f6ad421",
            "name": "F150W",
            "min_wavelength": 13310.0,
            "max_wavelength": 16700.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-imager-and-slitless-spectrograph/niriss-instrumentation/niriss-filters",
        },
        {
            "id": "d25da246-a17c-4cc2-aae6-cb82e2bee910",
            "name": "F158M",
            "min_wavelength": 14880.0,
            "max_wavelength": 16880.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-imager-and-slitless-spectrograph/niriss-instrumentation/niriss-filters",
        },
        {
            "id": "28927cec-5533-4c66-bd1e-2d1bd1068fb3",
            "name": "F380M",
            "min_wavelength": 37260.0,
            "max_wavelength": 39310.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-imager-and-slitless-spectrograph/niriss-instrumentation/niriss-filters",
        },
        {
            "id": "c396e5f9-e1b8-4843-a084-8182400148ce",
            "name": "F356W",
            "min_wavelength": 31410.0,
            "max_wavelength": 40680.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-imager-and-slitless-spectrograph/niriss-instrumentation/niriss-filters",
        },
        {
            "id": "10d7eac7-f920-4ab1-b3e7-43a00d003ca1",
            "name": "F090W",
            "min_wavelength": 7960.0,
            "max_wavelength": 10040.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-imager-and-slitless-spectrograph/niriss-instrumentation/niriss-filters",
        },
        {
            "id": "45527221-37af-41da-af27-ec18ed34e51f",
            "name": "F480M",
            "min_wavelength": 46690.0,
            "max_wavelength": 49710.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-imager-and-slitless-spectrograph/niriss-instrumentation/niriss-filters",
        },
        {
            "id": "dc5803b8-bc0c-4bf9-87ce-53f2f70d8e04",
            "name": "F140M",
            "min_wavelength": 13320.0,
            "max_wavelength": 14800.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-imager-and-slitless-spectrograph/niriss-instrumentation/niriss-filters",
        },
        {
            "id": "11cb59c8-9914-46c3-8435-e77e31f7a235",
            "name": "F115W",
            "min_wavelength": 10130.0,
            "max_wavelength": 12820.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-imager-and-slitless-spectrograph/niriss-instrumentation/niriss-filters",
        },
        {
            "id": "fd0e31cf-0e37-4a95-a85f-071504bfae16",
            "name": "F277W",
            "min_wavelength": 24130.0,
            "max_wavelength": 31420.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-imager-and-slitless-spectrograph/niriss-instrumentation/niriss-filters",
        },
        {
            "id": "cf96374a-f973-46b2-bc61-5938c9611675",
            "name": "F200W",
            "min_wavelength": 17510.0,
            "max_wavelength": 22260.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-imager-and-slitless-spectrograph/niriss-instrumentation/niriss-filters",
        },
    ],
    "JWST_NIRSPEC": [
        {
            "id": "9d7d5347-862b-4d05-b344-2f57ea8e99e7",
            "name": "prism",
            "min_wavelength": 6000.0,
            "max_wavelength": 53000.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-spectrograph/nirspec-instrumentation/nirspec-dispersers-and-filters",
        },
        {
            "id": "323a6d1c-9100-46a3-83b2-c8f1a2583c6c",
            "name": "F070lp",
            "min_wavelength": 7000.0,
            "max_wavelength": 12700.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-spectrograph/nirspec-instrumentation/nirspec-dispersers-and-filters",
        },
        {
            "id": "49146e26-ed4f-4b95-8d47-5b05347709f9",
            "name": "F100lp",
            "min_wavelength": 9700.0,
            "max_wavelength": 18900.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-spectrograph/nirspec-instrumentation/nirspec-dispersers-and-filters",
        },
        {
            "id": "35abbeba-d8ac-4413-ad11-5389ac4e373b",
            "name": "F170lp",
            "min_wavelength": 16600.0,
            "max_wavelength": 31700.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-spectrograph/nirspec-instrumentation/nirspec-dispersers-and-filters",
        },
        {
            "id": "d54f0133-0f51-4c13-8875-310ac2d37589",
            "name": "F295lp",
            "min_wavelength": 28700.0,
            "max_wavelength": 52700.0,
            "is_operational": True,
            "reference_url": "https://jwst-docs.stsci.edu/jwst-near-infrared-spectrograph/nirspec-instrumentation/nirspec-dispersers-and-filters",
        },
    ],
}
