name: CI
on:
  pull_request:
    branches: ["main"]
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  checks:
    strategy:
      matrix:
        test-target: [unit]

    uses: NASA-ACROSS/github-action-workflows/.github/workflows/workflow-ci-checks.yml@main
    with:
      runtime: python
